### ISSUE TITLE
Panic when using custom JOB_PLAN and LOG_LOCATION

### ISSUE THREAD

**Issue by brunosan** [Azure/azure-storage-azcopy#1155]
### Which version of the AzCopy was used? 
    AzCopy 10.6.0
### Which platform are you using? (ex: Windows, Mac, Linux)

Azure function on Powershell runtime.: 
>Machine: RD0003FF505A0E (Microsoft Windows NT 10.0.14393.0) Host Application: D:\Program Files (x86)\SiteExtensions\Functions\3.0.14287\workers\powershell\7\Microsoft.Azure.Functions.PowerShellWorker.dll --host 127.0.0.1 --port 51169 --workerId 95dda791-1941-497c-9d6e-55785d91d646 --requestId 5cb05eee-f303-4c26-b260-1ef5b36bf610 --grpcMaxMessageLength 2147483647 Process ID: 4052 PSVersion: 7.0.2 PSEdition: Core GitCommitId: 7.0.2 OS: Microsoft Windows 10.0.14393 Platform: Win32NT PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.2 PSRemotingProtocolVersion: 2.3 SerializationVersion: 1.1.0.1 WSManStackVersion: 3.0

### What command did you run?
```sh
$env:AZCOPY_JOB_PLAN_LOCATION=$TempFolder
$env:AZCOPY_LOG_LOCATION=$TempFolder
&"$TempFolder\AzCopy.exe" copy "$($url)" "$($DstFullPath)" --from-to BlobBlob
```

`$TempFolder` is `D:\local\Temp`

### What problem was encountered?

Unable to make a copy:

>panic: invalid state, azcopyAppPathFolder should be initialized by root  goroutine 1 [running]: github.com/Azure/azure-storage-azcopy/cmd.GetUserOAuthTokenManagerInstance.func1() 	/home/vsts/work/1/s/cmd/credentialUtil.go:59 +0x129 sync.(*Once).doSlow(0x12b3bb8, 0xc6e618) 	/opt/hostedtoolcache/go/1.13.0/x64/src/sync/once.go:66 +0xea sync.(*Once).Do(...) 	/opt/hostedtoolcache/go/1.13.0/x64/src/sync/once.go:57 github.com/Azure/azure-storage-azcopy/cmd.GetUserOAuthTokenManagerInstance(0x0) 	
/home/vsts/work/1/s/cmd/credentialUtil.go:57 +0x60 github.com/Azure/azure-storage-azcopy/cmd.oAuthTokenExists(0xc00001e410) 	
/home/vsts/work/1/s/cmd/credentialUtil.go:207 +0x4c github.com/Azure/azure-storage-azcopy/cmd.getBlobCredentialType(0xd88e20, 0xc0001c1200, 0xc00001e410, 0x42, 0x2030001, 0x0, 0x1bb070, 0x0) 	
/home/vsts/work/1/s/cmd/credentialUtil.go:138 +0x1af github.com/Azure/azure-storage-azcopy/cmd.doGetCredentialTypeForLocation(0xd88e20, 0xc0001c1200, 0x1297703, 0xc00001e410, 0x42, 0x0, 0x0, 0x1, 0xc6e610, 0xc000472440, ...) 	
/home/vsts/work/1/s/cmd/credentialUtil.go:401 +0x479 github.com/Azure/azure-storage-azcopy/cmd.getCredentialTypeForLocation(...) 	
/home/vsts/work/1/s/cmd/credentialUtil.go:390 github.com/Azure/azure-storage-azcopy/cmd.getCredentialInfoForLocation(0xd88e20, 0xc0001c1200, 0x3, 0xc00001e410, 0x42, 0x0, 0x0, 0x1, 0x0, 0x0, ...) 	
/home/vsts/work/1/s/cmd/credentialUtil.go:433 +0xc8 github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).initEnumerator(0xc0000e8380, 0x4edaf81b00000000, 0x7df7bd6c8e457747, 0xba58b3c8, 0x303000000000000, 0x0, 0x0, 0x0, 0x0, 0xc00001e730, ...) 	
/home/vsts/work/1/s/cmd/copyEnumeratorInit.go:31 +0x18b github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).processCopyJobPartOrders(0xc0000e8380, 0x0, 0x0) 	
/home/vsts/work/1/s/cmd/copy.go:1137 +0x5d5 github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).process(0xc0000e8380, 0x107, 0xb) 	
/home/vsts/work/1/s/cmd/copy.go:947 +0xbc github.com/Azure/azure-storage-azcopy/cmd.init.2.func2(0xc0001c2280, 0xc00005d080, 0x2, 0x4) 	
/home/vsts/work/1/s/cmd/copy.go:1517 +0x1ba github.com/spf13/cobra.(*Command).execute(0xc0001c2280, 0xc00005cfc0, 0x4, 0x4, 0xc0001c2280, 0xc00005cfc0) 	
/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2b1 github.com/spf13/cobra.(*Command).ExecuteC(0x128f800, 0xc00001d3a0, 0xc000125dc8, 0xc000125dc8) 	
/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2f1 github.com/spf13/cobra.(*Command).Execute(...) 	
/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 github.com/Azure/azure-storage-azcopy/cmd.Execute(0x0, 0x0, 0xc0000312f0, 0xd, 0xc000031300, 0xd, 0x7fffffff) 	
/home/vsts/work/1/s/cmd/root.go:140 +0xd6 main.main() 	/home/vsts/work/1/s/main.go:82 +0x3cb WARNING: Can't copy 

### How can we reproduce the problem in the simplest way?

Unfortunately I'am not yet able to consistently replicate the issue. Manual runs work ok, but left `cron` overnight starts to fail after a few hours (investigating)

### Have you found a mitigation/solution?

No.

**Comment by tasherif-msft** [comment]
Hi @brunosan we're very sorry for the lack of response on this. Are you still encountering this issue?

**Comment by brunosan** [comment]
I was unable to find a solution so I found a workaround using another tool. 
Thanks for reaching out @tasherif-msft.
