### ISSUE TITLE
panic: Unexpected status

### ISSUE THREAD

**Issue by hauntsaninja** [Azure/azure-storage-azcopy#1192]
### Which version of the AzCopy was used? 
```
$ ./azcopy --version
azcopy version 10.6.0
```

### Which platform are you using? (ex: Windows, Mac, Linux)
```
$ lsb_release -a
LSB Version:    core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
```
time ./azcopy sync 'https://{redacted storage account}.blob.core.windows.net/{redacted container}/?{redacted SAS}' 'https://{redacted other storage account}.blob.core.windows.net/{redacted container}/?{redacted SAS}'
```

### What problem was encountered?
azcopy crashed with:
```
panic: Unexpected status

goroutine 12064 [running]: 
github.com/Azure/azure-storage-azcopy/ste.(*jobPartMgr).updateJobPartProgress(...)
        /home/vsts/work/1/s/ste/mgr-JobPartMgr.go:662
github.com/Azure/azure-storage-azcopy/ste.(*jobPartMgr).ReportTransferDone(0xc0001e8160, 0xc000000001, 0x0)
        /home/vsts/work/1/s/ste/mgr-JobPartMgr.go:669 +0x2cc
github.com/Azure/azure-storage-azcopy/ste.(*jobPartTransferMgr).ReportTransferDone(0xc000226a80, 0xffffffff00000006)
        /home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:853 +0x5d
github.com/Azure/azure-storage-azcopy/ste.commonSenderCompletion(0xd7a8c0, 0xc000226a80, 0x7f4de55f9140, 0xc0081aa000, 0x800000, 0xc008188180, 0x16e, 0x55e81, 0xc008188000, 0x16d, ...)
        /home/vsts/work/1/s/ste/xfer-anyToRemote-file.go:603 +0x13a
github.com/Azure/azure-storage-azcopy/ste.epilogueWithCleanupSendToRemote(0xd7a8c0, 0xc000226a80, 0x7f4de55f9140, 0xc0081aa000, 0xd5f640, 0xc008194000)
        /home/vsts/work/1/s/ste/xfer-anyToRemote-file.go:558 +0x3b5
github.com/Azure/azure-storage-azcopy/ste.anyToRemote_file.func1()
        /home/vsts/work/1/s/ste/xfer-anyToRemote-file.go:349 +0x57
github.com/Azure/azure-storage-azcopy/ste.(*jobPartTransferMgr).runActionAfterLastChunk(...)
        /home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:521
github.com/Azure/azure-storage-azcopy/ste.(*jobPartTransferMgr).ReportChunkDone(0xc000226a80, 0xc008188180, 0x16e, 0x0, 0x55e81, 0xc226108eb4, 0xc226108eb8, 0xc0008f4678)
        /home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:508 +0x10f
github.com/Azure/azure-storage-azcopy/ste.createChunkFunc.func1(0xba)
        /home/vsts/work/1/s/ste/sender.go:180 +0x1a8
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).chunkProcessor(0xc0008e8000, 0xba)
        /home/vsts/work/1/s/ste/JobsAdmin.go:433 +0xdf
created by github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).poolSizer
        /home/vsts/work/1/s/ste/JobsAdmin.go:362 +0x67b
```
I don't see anything of interest in the log file azcopy creates...

### How can we reproduce the problem in the simplest way?
I don't have a simple repro for you, unfortunately. The crash does consistently repro for the storage account + container pair I'm trying to sync the data of.

### Have you found a mitigation/solution?
Not yet.

**Comment by zezha-msft** [comment]
@nakulkar-msft  Could you please take a look at this issue? The stack trace shows that it's related to updateJobPartProgress.
