### ISSUE TITLE
An error log remains on Windows Event Log when using AzCopy

### ISSUE THREAD

**Issue by v-takebi** [Azure/azure-storage-azcopy#1266]
When my customer use AzCopy with following command, an error log remains on Windows Event log.
But the process ends with success every time, and there is no failed logs on Azure Storage's Diagnostic logs.

If you have any information or knowledge about this issue, I'd like you to help me with this.

--- Command --------
```
azcopy.exe copy https://j*******e.file.core.windows.net/k***n/log/l*******e/*?se=2027-08-31t15%3A00%3A00z&sig=-REDACTED-&sp=rwdl&spr=https&srt=co&ss=f&st=2020-08-31t15%3A00%3A00z&sv=2019-12-12 https://yyyyyyyy.blob.core.windows.net/k***n-log?se=2027-08-31t15%3A00%3A00z&sig=-REDACTED-&sp=rwlacx&spr=https&srt=co&ss=b&st=2020-08-31t15%3A00%3A00z&sv=2019-12-12 --blob-type=BlockBlob 
```
--- Error logs ---------
```
The description for Event ID 0 from source 'C:\\k***n\\****\AzCopy\\azcopy.exe' cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event:

==> REQUEST/RESPONSE (Try=1/53.0347ms, OpTime=53.0347ms) -- REQUEST ERROR
   HEAD https://j*******e.file.core.windows.net/k***n/log/l*******e?se=2027-08-31t15%3A00%3A00z&sig=-REDACTED-&sp=rwdl&spr=https&srt=co&ss=f&st=2020-08-31t15%3A00%3A00z&sv=2019-12-12&timeout=901
   User-Agent: [AzCopy/10.7.0 Azure-Storage/0.8.0 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [a******4-6**9-4**f-5**4-6e*********7]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 404 The specified resource does not exist.
   Date: [Wed, 25 Nov 2020 11:00:36 GMT]
   Server: [Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [a******4-6**9-4**f-5**4-6e*********7]
   X-Ms-Error-Code: [ResourceNotFound]
   X-Ms-Request-Id: [a******6-2**a-0**f-5**a-c**********0]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-storage-file-go/azfile.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.8.0/azfile/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=ResourceNotFound) =====
Description=404 The specified resource does not exist., Details: (none)
   HEAD https://j*******e.file.core.windows.net/k***n/log/l*******e?se=2027-08-31t15%3A00%3A00z&sig=-REDACTED-&sp=rwdl&spr=https&srt=co&ss=f&st=2020-08-31t15%3A00%3A00z&sv=2019-12-12&timeout=901
   User-Agent: [AzCopy/10.7.0 Azure-Storage/0.8.0 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [a******4-6**9-4**f-5**4-6e*********7]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 404 The specified resource does not exist.
   Date: [Wed, 25 Nov 2020 11:00:36 GMT]
   Server: [Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [a******4-6**9-4**f-5**4-6e*********7]
   X-Ms-Error-Code: [ResourceNotFound]
   X-Ms-Request-Id: [a******6-2**a-0**f-5**a-c**********0]
   X-Ms-Version: [2019-02-02]


goroutine 1 [running]:
github.com/Azure/azure-storage-file-go/azfile.stack(0xc0001df2f0, 0xc0001fab00, 0xc0001dc240)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.8.0/azfile/zc_policy_request_log.go:146 +0xa4
github.com/Azure/azure-storage-file-go/azfile.NewRequestLogPolicyFactory.func1.1(0xd962c0, 0xc000788780, 0xc0000e5300, 0x12a96e0, 0xd962c0, 0xc000788780, 0xc000024430)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.8.0/azfile/zc_policy_request_log.go:96 +0x657
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0002023c0, 0xd962c0, 0xc000788780, 0xc0000e5300, 0xc000788780, 0xc000024430, 0x0, 0x24)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-file-go/azfile.NewRetryPolicyFactory.func1.1(0xd96300, 0xc0000b12c0, 0xc0000e5200, 0x10, 0xb27840, 0x64492d747301, 0xc0002086e0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.8.0/azfile/zc_policy_retry.go:194 +0x632
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc00004c1c0, 0xd96300, 0xc0000b12c0, 0xc0000e5200, 0xc000208798, 0x30, 0x28, 0x8)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-file-go/azfile.NewUniqueRequestIDPolicyFactory.func1.1(0xd96300, 0xc0000b12c0, 0xc0000e5200, 0x10, 0xb27840, 0x40d001, 0xc0002086e0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.8.0/azfile/zc_policy_unique_request_id.go:19 +0xb5
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000790000, 0xd96300, 0xc0000b12c0, 0xc0000e5200, 0xc000208780, 0x36, 0xc00001c380, 0xc00049d148)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
github.com/Azure/azure-storage-file-go/azfile.NewTelemetryPolicyFactory.func1.1(0xd96300, 0xc0000b12c0, 0xc0000e5200, 0x1, 0x0, 0x1, 0xc0000985c8)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.8.0/azfile/zc_policy_telemetry.go:34 +0x164
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0000b1830, 0xd96300, 0xc0000b12c0, 0xc0000e5200, 0xc0000b1830, 0xc0000b17d0, 0xc00049d218, 0x40d06f)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x4b
github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc00004c000, 0xd96300, 0xc0000b12c0, 0xd863c0, 0xc0001ce0a0, 0xc0000e5200, 0x1f, 0xc0000524a7, 0x14, 0x0)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:129 +0x88
github.com/Azure/azure-storage-file-go/azfile.fileClient.GetProperties(0xc000052480, 0x5, 0x0, 0x0, 0x0, 0xc000052488, 0x1f, 0xc0000524a7, 0x14, 0x0, ...)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.8.0/azfile/zz_generated_file.go:362 +0x34c
github.com/Azure/azure-storage-file-go/azfile.FileURL.GetProperties(...)
	/home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.8.0/azfile/url_file.go:155
github.com/Azure/azure-storage-azcopy/cmd.(*fileTraverser).getPropertiesIfSingleFile(0xc00004c0c0, 0x5, 0x0)
	/home/vsts/work/1/s/cmd/zc_traverser_file.go:55 +0x27e
github.com/Azure/azure-storage-azcopy/cmd.(*fileTraverser).traverse(0xc00004c0c0, 0x0, 0xc0000241a0, 0x12c6ce0, 0x0, 0x0, 0x0, 0x0)
	/home/vsts/work/1/s/cmd/zc_traverser_file.go:71 +0xb28
github.com/Azure/azure-storage-azcopy/cmd.(*copyEnumerator).enumerate(0xc00004c180, 0xc00004c180, 0x0)
	/home/vsts/work/1/s/cmd/zc_enumerator.go:629 +0x6e
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).processCopyJobPartOrders(0xc00005c380, 0x0, 0x0)
	/home/vsts/work/1/s/cmd/copy.go:1233 +0x88c
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).process(0xc00005c380, 0xb6, 0x0)
	/home/vsts/work/1/s/cmd/copy.go:1014 +0xbc
github.com/Azure/azure-storage-azcopy/cmd.init.16.func2(0xc0001ec000, 0xc0000240a0, 0x1, 0x1)
	/home/vsts/work/1/s/cmd/remove.go:79 +0x1ae
github.com/spf13/cobra.(*Command).execute(0xc0001ec000, 0xc000024060, 0x1, 0x1, 0xc0001ec000, 0xc000024060)
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x12a2800, 0xc0000f8460, 0xc000139dc8, 0x40d06f)
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2f1
github.com/spf13/cobra.(*Command).Execute(...)
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/Azure/azure-storage-azcopy/cmd.Execute(0xc000096420, 0x30, 0xc000096420, 0x30, 0xc000084880, 0x36, 0x7fffffff)
	/home/vsts/work/1/s/cmd/root.go:140 +0xd6
main.main()
	/home/vsts/work/1/s/main.go:82 +0x3cb
```

**Comment by neossian** [comment]
I experience a similar issue with Azcopy sync command showing 403 error event in Application log when the sync activity succeeded without error

--- Version ---
```
C:\admin>azcopy.exe -v
azcopy version 10.11.0

C:\admin>ver
Microsoft Windows [Version 6.3.9600]
```

--- AzCopy comand and output ---
```
 C:\admin>.\azcopy.exe sync 'c:\admin\backup' 'https://<redacted>.blob.core.windows.net/backups?sp=racwdl&st=202
1-09-03T18:22:35Z&se=2021-09-04T02:22:35Z&spr=https&sv=2020-08-04&sr=c&sig=<Redacted>'  --recursive --delete-destination true --log-level INFO --output-type text --exclude-path 'System Volume Information' --exclude-attributes S
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job e035e922-ee21-5341-66c8-434beda94c01 has started
Log file is located at: <redacted>\e035e922-ee21-5341-66c8-434beda94c01.log

0 Files Scanned at Source, 0 Files Scanned at Destination

Job e035e922-ee21-5341-66c8-434beda94c01 Summary
Files Scanned at Source: 1
Files Scanned at Destination: 1
Elapsed Time (Minutes): 0.0334
Number of Copy Transfers for Files: 0
Number of Copy Transfers for Folder Properties: 0
Total Number Of Copy Transfers: 0
Number of Copy Transfers Completed: 0
Number of Copy Transfers Failed: 0
Number of Deletions at Destination: 0
Total Number of Bytes Transferred: 0
Total Number of Bytes Enumerated: 0
Final Job Status: Completed
```

---- Windows Event ---
```
The description for Event ID 0 from source C:\admin\azcopy.exe cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

==> REQUEST/RESPONSE (Try=1/6.0023ms, OpTime=51.0472ms) -- RESPONSE STATUS CODE ERROR
   HEAD https://<redacted>/backups?se=2021-09-04t02%3A22%3A35z&sig=-REDACTED-&sp=racwdl&spr=https&sr=c&st=2021-09-03t18%3A22%3A35z&sv=2020-08-04&timeout=901
   User-Agent: [AzCopy/10.11.0 Azure-Storage/0.13 (go1.15; Windows_NT)]
   X-Ms-Client-Request-Id: [b455b962-97e6-450a-4208-c1ae8ea7df22]
   X-Ms-Version: [2019-12-12]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Date: [Fri, 03 Sep 2021 18:28:45 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [96b95a39-e01e-0041-57f1-a0b81a000000]
Response Details: 

```

**Comment by hantou** [comment]
My Customer had similar events warnings with Azcopy sync command.
What causes this event to be recorded?  it can be ignored?
ーーーーーーーーーー
The description for Event ID:0 in Source:'C:\tool\azcopy.exe' cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer. If the event originated on another computer, the display information had to be saved with the event. The following information was included with the event: ==> REQUEST/RESPONSE (Try=1/272.0018ms, OpTime=272.0018ms) -- REQUEST ERROR HEAD https://stsuzuyoazurefiles001.file.core.windows.net/suzuyo-azurefiles001/pre/urigen/order/log/app-2021-09-09.54.log?se=2050-12-31t12%3A50%3A28z&sig=-REDACTED-&sp=rwdlc&spr=https&srt=sco&ss=f&st=2021-06-16t04%3A50%3A28z&sv=2020-02-10&timeout=901 User-Agent: [AzCopy/10.10.0 Azure-Storage/0.8.0 (go1.15; Windows_NT)] X-Ms-Client-Request-Id: [439bb0f4-ea4f-4820-56c8-4d334b2499b7] X-Ms-Version: [2020-02-10] ------------------------------------------------------------------------

**Comment by mohsha-msft** [comment]
Hi, 

Thanks for reaching out!

AzCopy offers knob to disable application logging (Syslog/Windows Event Log). You can do that by setting environment variable `AZCOPY_DISABLE_SYSLOG`.

**Comment by hantou** [comment]
@mohsha-msft  Thank you. Could you please tell us the reason why this event is happening? can we ignore it?

**Comment by manuravikumar1** [comment]
f
