### ISSUE TITLE
panic: unexpected location, please specify if it is remote. Can't get job id to resume

### ISSUE THREAD

**Issue by rbavery** [Azure/azure-storage-azcopy#1327]
##### Note: The version is visible when running AzCopy without any argument
AzCopy 10.8.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Ubuntu 18.04
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

```
azcopy copy 'https://s3-us-west-2.amazonaws.com/aisurvey/' 'https://aiaiatrain.blob.core.windows.net/aiaiatrain' --recursive=true
```

### What problem was encountered?

```
→ azcopy jobs list     
panic: unexpected location, please specify if it is remote

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/common.Location.IsRemote(...)
	/home/vsts/work/1/s/common/fe-ste-models.go:449
github.com/Azure/azure-storage-azcopy/common.Location.IsLocal(...)
	/home/vsts/work/1/s/common/fe-ste-models.go:457
github.com/Azure/azure-storage-azcopy/common.(*FromTo).IsUpload(0xc000ff4e80, 0xc0000b2850)
	/home/vsts/work/1/s/common/fe-ste-models.go:557 +0xe1
github.com/Azure/azure-storage-azcopy/ste.(*jobMgr).setDirection(0xc0000b2780, 0x803)
	/home/vsts/work/1/s/ste/mgr-JobMgr.go:405 +0x2f
github.com/Azure/azure-storage-azcopy/ste.(*jobMgr).AddJobPart(0xc0000b2780, 0xfa4382f800000000, 0xc0007d0019, 0x32, 0xc000754080, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/vsts/work/1/s/ste/mgr-JobMgr.go:353 +0x2d6
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).ResurrectJobParts(0xc000098000)
	/home/vsts/work/1/s/ste/JobsAdmin.go:678 +0x1fd
github.com/Azure/azure-storage-azcopy/ste.ListJobs(0x64, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/vsts/work/1/s/ste/init.go:611 +0x6c
github.com/Azure/azure-storage-azcopy/cmd.inprocSend(0xc24fe2, 0x8, 0xbcb9c0, 0xc0000264d4, 0xaf23e0, 0xc0000211a0, 0x0, 0xc0000264d4)
	/home/vsts/work/1/s/cmd/rpc.go:50 +0x79b
github.com/Azure/azure-storage-azcopy/cmd.glob..func6(0xc24fe2, 0x8, 0xbcb9c0, 0xc0000264d4, 0xaf23e0, 0xc0000211a0)
	/home/vsts/work/1/s/cmd/rpc.go:36 +0x5d
github.com/Azure/azure-storage-azcopy/cmd.HandleListJobsCommand(0xc000000064, 0xc23381, 0x3)
	/home/vsts/work/1/s/cmd/jobsList.go:87 +0x93
github.com/Azure/azure-storage-azcopy/cmd.init.7.func2(0xc0001db900, 0x12c1ac8, 0x0, 0x0)
	/home/vsts/work/1/s/cmd/jobsList.go:67 +0x102
github.com/spf13/cobra.(*Command).execute(0xc0001db900, 0x12c1ac8, 0x0, 0x0, 0xc0001db900, 0x12c1ac8)
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x129e060, 0xc000149dd8, 0x0, 0x0)
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/Azure/azure-storage-azcopy/cmd.Execute(0xc000029020, 0x12, 0xc000029020, 0x12, 0xc000029080, 0x18, 0xfff)
	/home/vsts/work/1/s/cmd/root.go:141 +0xcf
main.main()
	/home/vsts/work/1/s/main.go:82 +0x3dd

```

### How can we reproduce the problem in the simplest way?
try copying from amazon 3 to azure storage. cancel the copy. restart computer. try to get the job id.
### Have you found a mitigation/solution?
no, other than recopying.

**Comment by mohsha-msft** [comment]
Hey @rbavery,

I tried to reproduce this issue but couldn't. Can you try reproducing it in the recent AzCopy version?
