### ISSUE TITLE
azcopy cleanup panics with large number of files in ~/.azcopy/

### ISSUE THREAD

**Issue by bmc-msft** [Azure/azure-storage-azcopy#1397]
### Which version of the AzCopy was used? 
10.9.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
`azcopy jobs clean --with-status=completed`

### What problem was encountered?
```
panic: open /home/USERNAME/.azcopy/plans/7841ce64-1c81-e34d-6782-cd92d6516ca3--00000.steV16: too many open files

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/common.PanicIfErr(...)
        /home/vsts/work/1/s/common/lifecyleMgr.go:564
github.com/Azure/azure-storage-azcopy/ste.JobPartPlanFileName.Map(0xc000d6fa5d, 0x32, 0x0)
        /home/vsts/work/1/s/ste/JobPartPlanFileName.go:60 +0x177
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).ResurrectJobParts(0xc00067c000)
        /home/vsts/work/1/s/ste/JobsAdmin.go:675 +0x168
github.com/Azure/azure-storage-azcopy/ste.ListJobs(0x64, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/vsts/work/1/s/ste/init.go:612 +0x6c
github.com/Azure/azure-storage-azcopy/cmd.inprocSend(0xed0cd5, 0x8, 0xe60020, 0x155f8c0, 0xd2efc0, 0xc000110330, 0xc0002a7a01, 0xc000110330)
        /home/vsts/work/1/s/cmd/rpc.go:50 +0x705
github.com/Azure/azure-storage-azcopy/cmd.glob..func6(0xed0cd5, 0x8, 0xe60020, 0x155f8c0, 0xd2efc0, 0xc000110330)
        /home/vsts/work/1/s/cmd/rpc.go:36 +0x5d
github.com/Azure/azure-storage-azcopy/cmd.handleCleanJobsCommand(0xc000000004, 0x7ffffdd3b5b6, 0x9)
        /home/vsts/work/1/s/cmd/jobsClean.go:94 +0xb1
github.com/Azure/azure-storage-azcopy/cmd.init.6.func2(0xc00065ef00, 0xc0005ae5e0, 0x0, 0x1)
        /home/vsts/work/1/s/cmd/jobsClean.go:60 +0x105
github.com/spf13/cobra.(*Command).execute(0xc00065ef00, 0xc0005ae5a0, 0x1, 0x1, 0xc00065ef00, 0xc0005ae5a0)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x15a3380, 0x46283ca1e6f7c059, 0x4bea55, 0xa0)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fe
github.com/spf13/cobra.(*Command).Execute(...)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/Azure/azure-storage-azcopy/cmd.Execute(0xc0005b21a0, 0x16, 0xc0005b21a0, 0x16, 0xc0005b2200, 0x1c, 0xfff)
        /home/vsts/work/1/s/cmd/root.go:144 +0x105
main.main()
```
### How can we reproduce the problem in the simplest way?

Note, I have 19385 files in `~/.azcopy` all together, with 8684 of those in `~/.azcopy/plans`

### Have you found a mitigation/solution?

Removing `--with-status=completed` succeeds, but with that argument failed repeatedly.

**Comment by jorgenpt** [comment]
I encountered this as well, we had about 135,000 files, each 3mb, in ~/.azcopy/plans. Running `azcopy clean jobs --with-status=Cancelled` would crash with the following error on Windows:

```
runtime: VirtualAlloc of 8003584 bytes failed with errno=1455
fatal error: out of memory
```

This was azcopy 10.3.4

**Comment by bmc-msft** [comment]
@nakulkar-msft what more information do you need?

**Comment by mohsha-msft** [comment]
https://github.com/Azure/azure-storage-azcopy/blob/87cba068b4cb797fb822163905cf6e92a4ec4db4/ste/init.go#L712 

I think the problem is that we're trying to create a list of all the items to be deleted in one go which could explain *out of memory* exception. Given the number of files, it makes sense to do it in small chunks (say 10,000I instead of cleaning in one go.

```go
for _, jobId := range jobIds {
		...

		if givenStatus == common.EJobStatus.All() || givenStatus == jpm.Plan().JobStatus() {
			listJobResponse.JobIDDetails = append(listJobResponse.JobIDDetails,
				common.JobIDDetails{JobId: jobId, CommandString: jpm.Plan().CommandString(),
					StartTime: jpm.Plan().StartTime, JobStatus: jpm.Plan().JobStatus()})
		}

               ...
	}
```

**Comment by siminsavani-msft** [comment]
Hi @bmc-msft ! Apologies in getting back to you! If you could, please try the latest [AzCopy](https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.16.2) version and let us know if you are still seeing issues or have any other questions! 

Thanks!

**Comment by gapra-msft** [comment]
Closing due to inactivity. Please feel free to reopen in case you are still experiencing this issue.
