### ISSUE TITLE
"invalid memory address or nil pointer dereference" Error during azcopy from file share to local

### ISSUE THREAD

**Issue by kayoshino** [Azure/azure-storage-azcopy#1421]
### Which version of the AzCopy was used? 
10.10.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
azcopy cp "https://storageacct.file.core.windows.net/someshare/somefolder/*" "F:\somefolder" --recursive --from-to=FileLocal

### What problem was encountered?
I'm consistently running into a 'nil pointer dereference' error when trying to copy from a file share to local.

```
100.0 %, 0 Done, 0 Failed, 0 Pending, 0 Skipped, 0 Total (scanning...), 
0.7 %, 215 Done, 0 Failed, 5005 Pending, 0 Skipped, 5220 Total, 2-sec Throughput (Mb/s): 4.5562

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xb00a05]

goroutine 10664 [running]:
github.com/Azure/azure-storage-azcopy/v10/ste.ErrorEx.ErrorCodeAndString(0x0, 0x0, 0x349085, 0x14bb480, 0xc001a25280, 0x1, 0xc002a4d790)
	/home/vsts/work/1/s/ste/ErrorExt.go:25 +0x45
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartTransferMgr).LogError(0xc00011dc70, 0xc0019cde60, 0x57, 0xc002870e70, 0xa2, 0x0, 0x0)
	/home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:842 +0x54
github.com/Azure/azure-storage-azcopy/v10/ste.epilogueWithCleanupDownload(0xf39580, 0xc00011dc70, 0xf24820, 0xc0020e7e60, 0xf1efe0, 0xc0000064c8, 0xf2a520, 0xc001fcf400)
	/home/vsts/work/1/s/ste/xfer-remoteToLocal-file.go:360 +0xa13
github.com/Azure/azure-storage-azcopy/v10/ste.remoteToLocal_file.func2()
	/home/vsts/work/1/s/ste/xfer-remoteToLocal-file.go:227 +0x70
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartTransferMgr).runActionAfterLastChunk(...)
	/home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:551
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartTransferMgr).ReportChunkDone(0xc00011dc70, 0xc0019cde60, 0x57, 0x0, 0x266, 0xc00387873c, 0xc003878740, 0x100563f01)
	/home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:538 +0x118
github.com/Azure/azure-storage-azcopy/v10/ste.createChunkFunc.func1(0x1)
	/home/vsts/work/1/s/ste/sender.go:181 +0x1eb
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).chunkProcessor(0xc0003a4820, 0x1)
	/home/vsts/work/1/s/ste/JobsAdmin.go:433 +0xdf
created by github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).poolSizer
	/home/vsts/work/1/s/ste/JobsAdmin.go:362 +0x6a5 

```
### How can we reproduce the problem in the simplest way?
Run a azcopy with --from-to=FileLocal and hit an error on this line 
https://github.com/Azure/azure-storage-azcopy/blob/045be76fb5a650d9dd69618df4bd85ae581c06fb/ste/xfer-remoteToLocal-file.go#L361

### Have you found a mitigation/solution?
It looks to me like a null error object is referenced after a recent code change. I've left a comment in the below PR. Hopefully my comment has the solution.

https://github.com/Azure/azure-storage-azcopy/pull/1402

**Comment by CheeseBreadIsGood** [comment]
I had this same issue. I was running version 10.10. Once I changed it back to version 10.8 it worked fine. I am assuming it was a bug in version 10.10.
