### ISSUE TITLE
`sync` Fails With Error: "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by chandlerkent** [Azure/azure-storage-azcopy#144]
### Which version of the AzCopy was used? 
10.0.4-Preview

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
`azcopy.exe sync 'some\path\that\exists' 'https://REDACTED.blob.core.windows.net/$web?sv=2015-04-05&sr=c&sig=REDACTED&se=2018-12-13T15%3A45%3A16Z&sp=rwdl' --recursive --force`

### What problem was encountered?
```
Job 57176550-9f6e-1049-40b5-5ed8cfb3fdf1 has started

Log file is located at: REDACTED/.azcopy/57176550-9f6e-1049-40b5-5ed8cfb3fdf1.log
0 File Scanned at Source, 0 Files Scanned at Destinationpanic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7ec49d]

goroutine 36 [running]:
github.com/Azure/azure-storage-azcopy/common.(*MMF).Unmap(0x0)
        /go/src/github.com/Azure/azure-storage-azcopy/common/mmf_windows.go:85 +0x2d
panic(0x9286a0, 0xd16f20)
        /usr/local/go/src/runtime/panic.go:502 +0x237
github.com/Azure/azure-storage-azcopy/common.(*MMF).Slice(...)
        /go/src/github.com/Azure/azure-storage-azcopy/common/mmf_windows.go:117
github.com/Azure/azure-storage-azcopy/ste.PutBlobUploadFunc(0xa3bdc0, 0xc042908700, 0xc04265a098, 0xc0427560c0, 0x5, 0x0
, 0x0, 0x0, 0xc0427560c8, 0x2d, ...)
        /go/src/github.com/Azure/azure-storage-azcopy/ste/xfer-localToBlockBlob.go:357 +0x12d
github.com/Azure/azure-storage-azcopy/ste.LocalToBlockBlob(0xa3bdc0, 0xc042908700, 0xa2cd00, 0xc042908680, 0xc042018280)

        /go/src/github.com/Azure/azure-storage-azcopy/ste/xfer-localToBlockBlob.go:94 +0x4b6
github.com/Azure/azure-storage-azcopy/ste.(*jobPartMgr).StartJobXfer(0xc0426da900, 0xa3bdc0, 0xc042908700)
        /go/src/github.com/Azure/azure-storage-azcopy/ste/mgr-JobPartMgr.go:423 +0x6c
github.com/Azure/azure-storage-azcopy/ste.(*jobPartTransferMgr).StartJobXfer(0xc042908700)
        /go/src/github.com/Azure/azure-storage-azcopy/ste/mgr-JobPartTransferMgr.go:101 +0x4e
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).transferAndChunkProcessor.func1(0xa3bdc0, 0xc042908700)
        /go/src/github.com/Azure/azure-storage-azcopy/ste/JobsAdmin.go:202 +0x1ab
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).transferAndChunkProcessor(0xc042618000, 0xb)
        /go/src/github.com/Azure/azure-storage-azcopy/ste/JobsAdmin.go:224 +0x144
created by github.com/Azure/azure-storage-azcopy/ste.initJobsAdmin
        /go/src/github.com/Azure/azure-storage-azcopy/ste/JobsAdmin.go:160 +0x508
```

Additionally, I see the following error in the Application Event Log:

```The description for Event ID 0 from source REDACTED\azcopy_windows_amd64_10.0.4\azcopy.exe cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

==> REQUEST/RESPONSE (Try=1/59.9993ms, OpTime=59.9993ms) -- RESPONSE STATUS CODE ERROR
   HEAD https://REDACTED.blob.core.windows.net/$web?se=2018-12-13t15%3A45%3A16z&sig=REDACTED&sp=rwdl&sr=c&sv=2015-04-05&timeout=901
   User-Agent: [AzCopy/10.0.4-Preview Azure-Storage/0.3 (go1.10.3; Windows_NT)]
   X-Ms-Client-Request-Id: [f47ed744-59ed-4951-7673-65648a2819a2]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Date: [Thu, 13 Dec 2018 14:48:17 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [ceeab95f-401e-00fd-0cf2-929e4f000000]
goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.stack(0xc0420c0150, 0xc042106100, 0xc0426ee000)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_policy_request_log.go:146 +0xae
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.NewRequestLogPolicyFactory.func1.1(0xa31c80, 0xc042104cc0, 0xc042622700, 0x9c501a, 0xc, 0x9c3f5d, 0xa)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_policy_request_log.go:96 +0x66c
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc04209a2d0, 0xa31c80, 0xc042104cc0, 0xc042622700, 0xa, 0x93f7a0, 0x1, 0xc042082198)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x4b
github.com/Azure/azure-storage-azcopy/ste.NewVersionPolicyFactory.func1.1(0xa31c80, 0xc042104cc0, 0xc042622700, 0x0, 0xc042695620, 0x42baeb, 0x9e7e10)
	/go/src/github.com/Azure/azure-storage-azcopy/ste/mgr-JobPartMgr.go:61 +0xef
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0420f0fc0, 0xa31c80, 0xc042104cc0, 0xc042622700, 0xc042695630, 0xc0426956f0, 0x4f53ea, 0xc042104cd0)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x4b
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.responderPolicy.Do(0xa2e100, 0xc0420f0fc0, 0xc04205a1e0, 0xa31c80, 0xc042104cc0, 0xc042622700, 0xc042104cd0, 0xa31cc0, 0xc042079680, 0x0)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zz_generated_responder_policy.go:33 +0x5a
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.anonymousCredentialPolicy.Do(0xa2e140, 0xc0420f0fe0, 0xa31c80, 0xc042104cc0, 0xc042622700, 0xd23c80, 0xa31c80, 0xc042104cc0, 0xc042057580)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_credential_anonymous.go:54 +0x56
github.com/Azure/azure-storage-azcopy/ste.NewBlobXferRetryPolicyFactory.func1.1(0xa31cc0, 0xc042079680, 0xc042622600, 0x9ca172, 0x16, 0xc042076690, 0x24)
	/go/src/github.com/Azure/azure-storage-azcopy/ste/xfer-retrypolicy.go:362 +0x6c8
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc04209a320, 0xa31cc0, 0xc042079680, 0xc042622600, 0x24, 0x5ef977, 0x95f540, 0xc0420796b0)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x4b
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.1(0xa31cc0, 0xc042079680, 0xc042622600, 0x9c415b, 0xa, 0xc04208a2c0, 0x3e)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_policy_unique_request_id.go:19 +0xa3
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0420f1000, 0xa31cc0, 0xc042079680, 0xc042622600, 0x3e, 0xc042082190, 0xc042079710, 0xc042695b10)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x4b
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1(0xa31cc0, 0xc042079680, 0xc042622600, 0x1, 0x0, 0x1, 0xc042082190)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_policy_telemetry.go:34 +0xa5
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc042079710, 0xa31cc0, 0xc042079680, 0xc042622600, 0xc042079710, 0x9c22e8, 0xc042695b80, 0x410def)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x4b
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc04205e680, 0xa31cc0, 0xc042079680, 0xa2e160, 0xc04205a1e0, 0xc042622600, 0x2d, 0xc04208a275, 0x5, 0x0)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:128 +0x88
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.blobClient.GetProperties(0xc04208a240, 0x5, 0x0, 0x0, 0x0, 0xc04208a248, 0x2d, 0xc04208a275, 0x5, 0x0, ...)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zz_generated_blob.go:657 +0x3c1
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.BlobURL.GetProperties(0xc04208a240, 0x5, 0x0, 0x0, 0x0, 0xc04208a248, 0x2d, 0xc04208a275, 0x5, 0x0, ...)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/url_blob.go:113 +0x126
github.com/Azure/azure-storage-azcopy/cmd.(*syncUploadEnumerator).listTheSourceIfRequired(0xc0426a2000, 0xc04210a1e0, 0xa2cd00, 0xc04205e680, 0x0, 0x0, 0x0)
	/go/src/github.com/Azure/azure-storage-azcopy/cmd/syncUploadEnumerator.go:181 +0x500
github.com/Azure/azure-storage-azcopy/cmd.(*syncUploadEnumerator).enumerate(0xc0426a2000, 0xc04210a1e0, 0x9c1afd, 0x1)
	/go/src/github.com/Azure/azure-storage-azcopy/cmd/syncUploadEnumerator.go:536 +0x32e
github.com/Azure/azure-storage-azcopy/cmd.(*cookedSyncCmdArgs).process(0xc04210a1e0, 0xbc, 0xc042090000)
	/go/src/github.com/Azure/azure-storage-azcopy/cmd/sync.go:437 +0x5da
github.com/Azure/azure-storage-azcopy/cmd.init.13.func2(0xc04213ec80, 0xc04205e1c0, 0x2, 0x4)
	/go/src/github.com/Azure/azure-storage-azcopy/cmd/sync.go:485 +0x182
github.com/Azure/azure-storage-azcopy/vendor/github.com/spf13/cobra.(*Command).execute(0xc04213ec80, 0xc04205e100, 0x4, 0x4, 0xc04213ec80, 0xc04205e100)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/spf13/cobra/command.go:766 +0x2c8
github.com/Azure/azure-storage-azcopy/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xd1e820, 0xd, 0x56, 0x18)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/spf13/cobra/command.go:852 +0x311
github.com/Azure/azure-storage-azcopy/vendor/github.com/spf13/cobra.(*Command).Execute(0xd1e820, 0x16, 0xd)
	/go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/spf13/cobra/command.go:800 +0x32
github.com/Azure/azure-storage-azcopy/cmd.Execute(0xc042060440, 0x16, 0xc042060440, 0x16)
	/go/src/github.com/Azure/azure-storage-azcopy/cmd/root.go:71 +0x84
main.main()
	/go/src/github.com/Azure/azure-storage-azcopy/main.go:55 +0x199
```

And this is the contents of the log file that is created:
```
2018/12/13 14:45:48 AzcopVersion  10.0.4-Preview
2018/12/13 14:45:48 OS-Environment  windows
2018/12/13 14:45:48 OS-Architecture  amd64
2018/12/13 14:45:48 ERR: [P#0-T#0] UPLOADFAILED: REDACTED : 000 : PutBlob Failed CreateFileMapping: Not enough storage is available to process this command.
   Dst: https://REDACTED.blob.core.windows.net/$web/REDACTED?se=2018-12-13t15%3A45%3A16z&sig=REDACTED&sp=rwdl&sr=c&sv=2015-04-05
```

I've also set up Fiddler as a proxy to capture the web traffic, and I see the following requests:

```
HEAD https://REDACTED.blob.core.windows.net/$web?se=2018-12-13T15%3A45%3A16Z&sig=SlSSrC3H%2F6NdQyXADJA1UfdSVxhG6XFk%2FJ2gD%2FGt5As%3D&sp=rwdl&sr=c&sv=2015-04-05&timeout=901
403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. ()
```

AND

```
GET https://REDACTED.blob.core.windows.net/$web?comp=list&restype=container&se=2018-12-13T15%3A45%3A16Z&sig=SlSSrC3H%2F6NdQyXADJA1UfdSVxhG6XFk%2FJ2gD%2FGt5As%3D&sp=rwdl&sr=c&sv=2015-04-05&timeout=901
200 OK (application/xml)
```

So the request to list the container _works_, but a preceding HEAD request is failing with a 403.

### How can we reproduce the problem in the simplest way?
Haven't found a reduction for this yet. This process is part of an Azure DevOps Pipeline and has been working as of two weeks ago. When we did a release yesterday, it failed. Here is the relevant parts of the release process:
1. Download AZCopy v10 from https://aka.ms/downloadazcopy-v10-windows
1. Extract the zip into a folder
1. Generate a SAS URL using:
`New-AzureStorageContainerSASToken -Name '$web' -Permission rwdl -Context $storageAccount.Context`
1. Prepare the build artifact
1. Perform `sync` command with AZCopy:
`azcopy.exe sync 'some\path\that\exists' 'https://REDACTED.blob.core.windows.net/$web?sv=2015-04-05&sr=c&sig=REDACTED&se=2018-12-13T15%3A45%3A16Z&sp=rwdl' --recursive --force`

![image](https://user-images.githubusercontent.com/13843/49946800-ba241100-febd-11e8-9331-c668245801df.png)

I am able to reproduce using Powershell directly using the same parameters that the pipeline is using. So I have eliminated the pipeline as the source of the issue.

### Have you found a mitigation/solution?
No I haven't found a workaround yet.

**Comment by chandlerkent** [comment]
It looks like it may have something to do with how the signature is being constructed for the HEAD request. I used Fiddler to modify the request so I could get more information from the Storage Account. The original request was a `HEAD` which looked like:

```
HEAD https://REDACTED.blob.core.windows.net/$web?se=2018-12-13T20%3A11%3A27Z&sig=REDACTED&sp=rwdl&sr=c&sv=2015-04-05&timeout=901 HTTP/1.1
Host: REDACTED.blob.core.windows.net
User-Agent: AzCopy/10.0.4-Preview Azure-Storage/0.3 (go1.10.3; Windows_NT)
X-Ms-Client-Request-Id: 759a9bef-75d0-46df-40df-9c269f6b552c
X-Ms-Version: 2018-03-28
```

I replaced the `HEAD` method with a `GET` to coax the Storage Account from giving me more information about the 403 response. This is the response it gives:

```
HTTP/1.1 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
Content-Length: 503
Content-Type: application/xml
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: 0f3ffa99-901e-003e-201a-93da00000000
x-ms-error-code: AuthenticationFailed
Date: Thu, 13 Dec 2018 19:31:40 GMT

<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:0f3ffa99-901e-003e-201a-93da00000000
Time:2018-12-13T19:31:40.6182868Z</Message><AuthenticationErrorDetail>Signature did not match. String to sign used was rwdl

2018-12-13T20:11:27Z
/blob/REDACTED/$root



2015-04-05




</AuthenticationErrorDetail></Error>
```

Based on what it is telling me, I think the issue is that it is trying to perform something against the container `$root`, even though the request URL has `$web` as the container name.

**Comment by chandlerkent** [comment]
I have tried it today completely outside of the Azure DevOps Pipeline to confirm there was nothing weird with the pipeline itself. I have reproduced this issue in two ways:
1. Generating a SAS URL through Azure Powershell and calling `azcopy` with that SAS URL.
1. Generated a SAS URL with Azure Storage Explorer and calling `azcopy` with that SAS URL.

Both ways reproduced the same issue as detailed above.

**Comment by chandlerkent** [comment]
I was able to work around this issue by generating a Storage Account SAS instead of a Container SAS. I switched my code to:

`New-AzureStorageAccountSASToken -Service Blob -ResourceType Container, Object -Permission rwdl -Context $storageAccount.Context`

However, this is granting more permissions than I want to since I know I am deploying into a single container.

**Comment by zezha-msft** [comment]
Hi @chandlerkent, thanks for reaching out!

I'll look into this issue and get back to you shortly.

Btw I see an error message in the log "Not enough storage is available to process this command." Does your disk happen to be full or close to being full?

**Comment by chandlerkent** [comment]
@zezha-msft thanks for the update. No the disk on the machines I've tested this on are not full.

**Comment by seguler** [comment]
What is the source disk ? Could it be a mounted file share instead of a disk ? THe original crash is something to do with the underlying source from the logs.

**Comment by chandlerkent** [comment]
@zezha-msft that would make sense because the version of AZCopy had not changed between when this was working and when this was not working.

Since the fault probably lies in another service, do I need to open a support case with them instead?

**Comment by zezha-msft** [comment]
Hi @chandlerkent, sorry, I just realized that I made a mistake while trying to repro this problem: I forgot to escape the dollar sign in `$web` and ended up targeting the wrong container and getting a similar error message to yours. But once I fixed my mistake, everything works fine for me. 

I took a deeper look into the code, and discovered that the 403 error that you are seeing is actually benign and expected. In the sync workflow, we make a request to the destination to see whether it's a blob or not(since we could have blobs in the root container, whose URL might look like a container). The HEAD request failed because we were pretending that it's a blob and didn't include restype=container. 

AzCopy crashed because it couldn't memory-map the file to upload. On what kind of storage is your source data being hosted? Could you reproduce the same problem on your local machine?

If you prefer, we can schedule some time to work on this issue together. Feel free to include @seguler as he has a lot of experience with different environments.

**Comment by chandlerkent** [comment]
Hi @zezha-msft, thanks for the update. The source is an Azure standard data disk attached to an Azure Windows 2012 R2 VM. This has been reproduced across 4 separate VMs in the same configuration. I have not tried to reproduce on a local environment yet. I can do that when I next get some time.

I am also happy to have a meeting with you. I'm not sure how you'd like to coordinate.

**Comment by zezha-msft** [comment]
Hi @chandlerkent, please try the same command on a local environment if you have time.

For scheduling a meeting, you can find any free spot on my calendar that's convenient for you. Thanks!

**Comment by zezha-msft** [comment]
Hi @chandlerkent, it's great to hear that the problem is not occurring anymore. It seems like some kind of glitch in the OS when it tries to create a memory-mapped file.

We are moving away from using memory-mapped files in this project, so hopefully in the future this problem will not occur anymore.

Please let us know if you encounter this issue again. We'd be happy to assist you.
