### ISSUE TITLE
Cannot download from azurite with hostname

### ISSUE THREAD

**Issue by tomasgiden** [Azure/azure-storage-azcopy#1480]
##### Note: The version is visible when running AzCopy without any argument
10.10.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Inside docker Linux docker compose container environment (with windows as host). docker compose contains two containers. Container 1: Based on python:latest and azcopy added with "RUN wget -O azcopy_v10.tar.gz https://aka.ms/downloadazcopy-v10-linux && tar -xf azcopy_v10.tar.gz --strip-components=1 && cp ./azcopy /usr/bin/"

Container 2 (azurite as label): 
mcr.microsoft.com/azure-storage/azurite

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
Inside container 1:
azcopy cp "http://azurite:10000/devstoreaccount1/63098e55-b3fc-4b2f-99c3-14338bc9c540?se=2021-06-18T12%3A32%3A33Z&sp=rwl&sv=2020-06-12&ss=b&srt=sco&sig=VvyhT9ZPpvuCkyabeiUi%2BYUMxPrVlnKKZEEM6SIC32w%3D" "./test_dataset_out" --from-to BlobLocal --recursive

Where azurite is the hostname that corresponds to Container 2

AND

azcopy cp "http://172.19.0.2:10000/devstoreaccount1/63098e55-b3fc-4b2f-99c3-14338bc9c540?se=2021-06-18T12%3A32%3A33Z&sp=rwl&sv=2020-06-12&ss=b&srt=sco&sig=VvyhT9ZPpvuCkyabeiUi%2BYUMxPrVlnKKZEEM6SIC32w%3D" "./test_dataset_out" --from-to BlobLocal --recursive

which is identical to the first command but where 172.19.0.2 is the azurite hostname converted to IP-address

### What problem was encountered?
When using the host-name, no files are transferred. When using the ip-address all files are transferred as expected.

**When uploading files into azurite, it works with hostname!** There I don't have to convert it to an ip-address.

### Have you found a mitigation/solution?
Convert from hostname to IP-address

**Comment by manumsft** [comment]
@tomasgiden - feel that this could be something specific to a docker setup. would you be able to test it in a simpler environment with two machines?

**Comment by gapra-msft** [comment]
Closing this issue due to inactivity. Please reopen an issue if you are still experiencing an issue with AzCopy

**Comment by liammoat** [comment]
> Closing this issue due to inactivity. Please reopen an issue if you are still experiencing an issue with AzCopy

Hello @gapra-msft - I am also experiencing this issue. There is something odd happening when synchronising with azurite using its docker hostname. I see this on the client side:

```
Cannot perform sync due to error: cannot list files due to reason GET http://azurite:10000/devstoreaccount1
--------------------------------------------------------------------------------
RESPONSE 403: 403 This request is not authorized to perform this operation using this resource type.
ERROR CODE: AuthorizationResourceTypeMismatch
--------------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
  <Code>AuthorizationResourceTypeMismatch</Code>
  <Message>This request is not authorized to perform this operation using this resource type.
RequestId:4d805d68-4265-457e-ba25-1abb42fc87a1
Time:2024-05-24T14:59:51.010Z</Message>
</Error>
```

And this on the server side: 
```
2024-05-24T11:06:07.966Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 info: AccountSASAuthenticator:validate() Start validation against account Shared Access Signature pattern.
2024-05-24T11:06:07.966Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 debug: AccountSASAuthenticator:validate() Getting account properties...
2024-05-24T11:06:07.966Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 debug: AccountSASAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: undefined, blob: 
2024-05-24T11:06:07.966Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 debug: AccountSASAuthenticator:validate() Got account properties successfully.
2024-05-24T11:06:07.966Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 debug: AccountSASAuthenticator:validate() Retrieved signature from URL parameter sig: KCcDG5jJ0CmqD1KR7sH9+XvD2doHrGgg3NhwxfyjA4E=
2024-05-24T11:06:07.967Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 debug: AccountSASAuthenticator:validate() Successfully got valid account SAS values from request. {"version":"2018-03-28","expiryTime":"2024-05-25T11:06:07Z","permissions":"rwdlac","services":"b","resourceTypes":"co"}
2024-05-24T11:06:07.967Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 info: AccountSASAuthenticator:validate() Validate signature based account key1.
2024-05-24T11:06:07.967Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 debug: AccountSASAuthenticator:validate() String to sign is: "devstoreaccount1\nrwdlac\nb\nco\n\n2024-05-25T11:06:07Z\n\n\n2018-03-28\n"
2024-05-24T11:06:07.967Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 debug: AccountSASAuthenticator:validate() Calculated signature is: KCcDG5jJ0CmqD1KR7sH9+XvD2doHrGgg3NhwxfyjA4E=
2024-05-24T11:06:07.967Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 info: AccountSASAuthenticator:validate() Signature based on key1 validation passed.
2024-05-24T11:06:07.967Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 info: AccountSASAuthenticator:validate() Validate start and expiry time.
2024-05-24T11:06:07.967Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 info: AccountSASAuthenticator:validate() Validate IP range.
2024-05-24T11:06:07.967Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 info: AccountSASAuthenticator:validate() Validate request protocol.
2024-05-24T11:06:07.967Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 debug: AccountSASAuthenticator:validate() Got permission requirements for operation Service_ListContainersSegment - {"service":"b","resourceType":"s","permission":"l"}
2024-05-24T11:06:07.967Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2024-05-24T11:06:07.967Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=This request is not authorized to perform this operation using this resource type.  ErrorHTTPStatusCode=403 ErrorHTTPStatusMessage=This request is not authorized to perform this operation using this resource type. ErrorHTTPHeaders={"x-ms-error-code":"AuthorizationResourceTypeMismatch","x-ms-request-id":"c2f260a4-bf09-4cc8-a032-8c0a261a1c36"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>AuthorizationResourceTypeMismatch</Code>\n  <Message>This request is not authorized to perform this operation using this resource type.\nRequestId:c2f260a4-bf09-4cc8-a032-8c0a261a1c36\nTime:2024-05-24T11:06:07.967Z</Message>\n</Error>" ErrorStack="StorageError: This request is not authorized to perform this operation using this resource type.\n    at StorageErrorFactory.getAuthorizationResourceTypeMismatch (/opt/azurite/dist/src/blob/errors/StorageErrorFactory.js:177:16)\n    at AccountSASAuthenticator.validate (/opt/azurite/dist/src/blob/authentication/AccountSASAuthenticator.js:107:49)\n    at AuthenticationMiddlewareFactory.authenticate (/opt/azurite/dist/src/blob/middlewares/AuthenticationMiddlewareFactory.js:35:40)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
2024-05-24T11:06:07.967Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 error: ErrorMiddleware: Set HTTP code: 403
2024-05-24T11:06:07.967Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 error: ErrorMiddleware: Set HTTP status message: This request is not authorized to perform this operation using this resource type.
2024-05-24T11:06:07.967Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=AuthorizationResourceTypeMismatch
2024-05-24T11:06:07.967Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=c2f260a4-bf09-4cc8-a032-8c0a261a1c36
2024-05-24T11:06:07.968Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 error: ErrorMiddleware: Set content type: application/xml
2024-05-24T11:06:07.968Z c2f260a4-bf09-4cc8-a032-8c0a261a1c36 error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>AuthorizationResourceTypeMismatch</Code>\n  <Message>This request is not authorized to perform this operation using this resource type.\nRequestId:c2f260a4-bf09-4cc8-a032-8c0a261a1c36\nTime:2024-05-24T11:06:07.967Z</Message>\n</Error>"
```

When running the exact same test, but using azurite's IP address, it works without a problem.
