### ISSUE TITLE
Exit codes documentation is missing

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-storage-azcopy#1507]
Without having exit codes documented, the experience to troubleshoot what happened remotely (in this case the command is executed in Azure Function) is very challenging. Please document exit codes.

### Which version of the AzCopy was used? 

Version 10 (latest)

### Which platform are you using? (ex: Windows, Mac, Linux)

Linux

### What command did you run?

```
azcopy cp "{sourcePath}/*.*" "{destination}" --from-to LocalBlob --check-length=false");
```

where `sourcePath` is a local folder and `destination` is a blob URI with SAS token (can write)

### What problem was encountered?

This is all I got from azcopy's failure to run:

```
**exit code 2**
```

log files have showed the following:

```
panic: mkdir : The system cannot find the path specified.
goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/v10/common.PanicIfErr(...)
/home/vsts/work/1/s/common/lifecyleMgr.go:583
main.main()
/home/vsts/work/1/s/main.go:55 +0x589
```

### How can we reproduce the problem in the simplest way?

N/A

### Have you found a mitigation/solution?

No

**Comment by zezha-msft** [comment]
Hi @SeanFeldman thanks for reaching out!

Could you please post the full trace?

The reason why we don't document the exit code is because it's not used for diagnosis. Under normal circumstances, the tool exits with 0 with success, or 1 with error. In this case the tool panicked, which suggests that something truly unexpected happened. We'd like to investigate further if you could provide more details.

**Comment by SeanFeldman** [comment]
@zezha-msft, I wish I had more, but this is all that was logged. Allow me to extend on how it is used.

An Azure Function is invoking azcopy as an external process. The code subscribes to both `.OutputDataReceived` and `ErrorDataReceived` events of the process, additionally logging the exit code of the process. Everything I've shared above is coming from those two events. Nothing more. I've briefly looked at the Go code and saw the "panic" path, but what I didn't see there is what with .NET would be an exception thrown with the details of the error.

I've also briefly looked into retrieving the log file for azcopy, but I'm not sure how to achieve that given it's a function on the Consumption plan, and I have no access to the file.

**Comment by zezha-msft** [comment]
Hi @SeanFeldman, I think I know what's going on.

The panic was caused by an unexpected failure to create the directory which will hold the logs. On linux, it's usually $HOME/.azcopy, but it sounds like in your environment that's not valid. Could you please try setting these two variables:

export AZCOPY_JOB_PLAN_LOCATION=<value>
export AZCOPY_LOG_LOCATION=<value>

Please set them to a path that you know for sure is valid. Please let me know if that works, we can add some documentation for this issue and also improve the behavior in this case (we haven't seen it before, panics are reserved for situations that are truly unexpected need fixing from the devs).

**Comment by zezha-msft** [comment]
Doc link: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-configure?toc=/azure/storage/blobs/toc.json#change-the-location-of-plan-files

**Comment by SeanFeldman** [comment]
@zezha-msft, an update. After having a few messages failing and later retrying the specific function invocation, azcopy works... so w/o setting up any environment variables (Consumption mode, Windows), it started to work w/o doing anything. I'm very concerned as I'm literally blind and clueless about that and worried this could happen again.

**Comment by zezha-msft** [comment]
Hi @SeanFeldman, that's quite surprising, I think it might have more to do with the Function environment than AzCopy itself. 

Interestingly, we also have an Azure Function launching AzCopy jobs (as part of an internal application). Perhaps @adreed-msft  could give some pointers here.

**Comment by seankearney** [comment]
@zezha-msft & @SeanFeldman -- I can provide some more details on this problem as it is happening now in our environment.

1. This is a *Windows* Azure Function (Runtime 3.1.3).
2. We've had the function fail a dozen times and it is not recovering/working.
3. Using Kudu, if I try to locate the `.azcopy` directory I can find `C:\local\UserProfile\>`. But there is no `.azcopy` directory.
4. Using Kudu to confirm, I was able to run `azcopy env` and we are not overriding the default value for the `AZCOPY_JOB_PLAN_LOCATION` and `AZCOPY_LOG_LOCATION` variables.

### Environment Variables

```
PS C:\home>  [Environment]::GetEnvironmentVariables()


Name                           Value                                           
----                           -----                                           

AZURE_FUNCTIONS_ENVIRONMENT    Production                                      

ProgramData                    C:\local\ProgramData                            

SystemRoot                     C:\Windows                                      
SystemDrive                    C:                                              
WEBSITE_PLATFORM_VERSION       94.0.7.116                                      
NUGET_PACKAGES                 C:\home\.nuget\                                 

USERPROFILE                    C:\local\UserProfile                            

CommonProgramFiles(x86)        C:\Program Files (x86)\Common Files             

PUBLIC                         C:\Users\Public                                 
```

### `azcopy env`

```
PS C:\home\site\wwwroot\bin\Hls\tools> .\azcopy env
.\azcopy env
INFO: Name: AZCOPY_LOG_LOCATION
Current Value: 
Description: Overrides where the log files are stored, to avoid filling up a disk.

INFO: Name: AZCOPY_JOB_PLAN_LOCATION
Current Value: 
Description: Overrides where the job plan files (used for progress tracking and resuming) are stored, to avoid filling up a disk.
```

**Comment by seankearney** [comment]
To followup on this, I set the environment variables by setting "App Settings" in the Azure function portal, which appears to override the defaults.

```
PS C:\home\site\wwwroot\Hls\tools> .\azcopy env
.\azcopy env
INFO: Name: AZCOPY_LOG_LOCATION
Current Value: C:\local\Temp\
Description: Overrides where the log files are stored, to avoid filling up a disk.

INFO: Name: AZCOPY_JOB_PLAN_LOCATION
Current Value: C:\local\Temp\
Description: Overrides where the job plan files (used for progress tracking and resuming) are stored, to avoid filling up a disk.
```

I've executed the functions, but azcopy didn't create any logs/plans. Still getting `AzCopy FAILED with exit code 2.`

```
PS C:\local\Temp> dir
dir
    Directory: C:\local\Temp

Mode                LastWriteTime         Length Name                          
----                -------------         ------ ----                          
d-----        8/12/2021   3:40 PM                jobs                          
d-----        8/12/2021   3:40 PM                JobsShutdown                  
d-----        8/12/2021   3:40 PM                siteExtLogs                   

```

**Comment by adreed-msft** [comment]
Is this the same panic or a different error?

**Comment by zezha-msft** [comment]
I would also suggest to reach out to the Azure Functions support team for help. This is not actionable for us at this point.

**Comment by seankearney** [comment]
I apologize -- I went back to double check logs and after I added the environment variables azcopy is working! So, to sum it up, by manually setting `AZCOPY_LOG_LOCATION` & `AZCOPY_JOB_PLAN_LOCATION` to `C:\local\Temp` azcopy is now working.

How could we sum this issue up then? azcopy, when running in a Function, doesn't have permission to create the `.azcopy` directory in the "USERPROFILE" directory and therefore we need to explicitly set those two settings?

**Comment by zezha-msft** [comment]
@seankearney glad to hear you are unblocked.

It is quite strange that the error didn't always happen. In fact, @adreed-msft also implemented an Azure Function that called AzCopy but didn't encounter it. We should improve the error message regardless though. Thanks for your findings.

**Comment by SeanFeldman** [comment]
@zezha-msft, absolutely. Having a meaningful error message would help.

**Comment by zezha-msft** [comment]
Summary note: provide a more meaningful error instead of panic for failure to create log directory.

**Comment by dphulkar-msft** [comment]
We recommend trying the latest version of Azcopy (10.28.1) to see if it resolves the issue. We will go ahead and close the ticket for now. Please feel free to reopen it if you continue to experience the issue after updating to the latest version.

Thank you for your patience!
