### ISSUE TITLE
azcopy command couldn't create job part plan file.

### ISSUE THREAD

**Issue by Mustk4824** [Azure/azure-storage-azcopy#1532]
### Which version of the AzCopy was used? 
AzcopyVersion  10.5.0
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux

### What command did you run?
azcopy cp "/path/to/file.txt" "https://[account].blob.core.windows.net/[container]/[path/to/blob]?[SAS]"
### What problem was encountered?
Unable to copy to Blob Storage, when the file size is over 1.7 GB but less 1.7 GB, there is no issue. Below is the error message i am getting in stderr
panic: couldn't create job part plan file "19263cc2-a4cf-4947-6d99-1fd94954e10f--00000.steV14": open /root/.azcopy/plans/19263cc2-a4cf-4947-6d99-1fd94954e10f--00000.steV14: no space left on device

### How can we reproduce the problem in the simplest way?

1. I am running azcopy command in a simple shell script with find, tar and azcopy commands in it. This script we are using to backup our hourly incremental backup and schedule to run hourly with crontab. Just for info, we have 4 cpu and 8 GB of RAM on the machine.

2. When i try to check the log of /root/.azcopy/plans/19263cc2-a4cf-4947-6d99-1fd94954e10f.log. The output is no such file or directory. When i run the same command with successful created backup, this is what i am getting, if it helps. 

head -n 20 /root/.azcopy/ce851fb2-d2f5-1b4d-4f22-c3bb115efbf4.log
2021/08/27 14:56:20 AzcopyVersion  10.5.0
2021/08/27 14:56:20 OS-Environment  linux
2021/08/27 14:56:20 OS-Architecture  amd64
2021/08/27 14:56:20 Log times are in UTC. Local time is 27 Aug 2021 10:56:20
2021/08/27 14:56:20 Job-Command copy Hourly_incre_backup_2021-08-27-1055.tar.gz https://[account].blob.core.windows.net/[container]/[path/to/blob]?se=2026-01-01t00%3A53%3A00z&sig=-REDACTED-&sp=rwdlacx&spr=https%2Chttp&srt=sco&ss=b&st=2020-07-22t15%3A53%3A00z&sv=2019-10-10
2021/08/27 14:56:20 Number of CPUs: 4
2021/08/27 14:56:20 Max file buffer RAM 2.000 GB
2021/08/27 14:56:20 Max concurrent network operations: 32 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2021/08/27 14:56:20 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2021/08/27 14:56:20 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2021/08/27 14:56:20 Max enumeration routines: 16 (Based on hard-coded default. Set AZCOPY_CONCURRENT_SCAN environment variable to override)
2021/08/27 14:56:20 Parallelize getting file properties (file.Stat): false (Based on AZCOPY_PARALLEL_STAT_FILES environment variable)
2021/08/27 14:56:20 Max open files when downloading: 3672 (auto-computed)
2021/08/27 14:56:20 ISO 8601 START TIME: to copy files that changed after this job started, use the parameter --include-after=2021-08-27T14:56:15Z
2021/08/27 14:56:20 Any empty folders will not be processed, because source and/or destination doesn't have full folder support
2021/08/27 14:56:20 Final job part has been created
2021/08/27 14:56:20 PERF: primary performance constraint is Unknown. States: X:  0, O:  0, M:  0, L:  0, R:  0, D:  0, W:  0, F:  0, B:  0, E:  0, T:  0, GRs:  0
2021/08/27 14:56:20 0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total,
2021/08/27 14:56:20 JobID=ce851fb2-d2f5-1b4d-4f22-c3bb115efbf4, credential type: Anonymous
2021/08/27 14:56:20 scheduling JobID=ce851fb2-d2f5-1b4d-4f22-c3bb115efbf4, Part#=0, Transfer#=0, priority=0
### Have you found a mitigation/solution?
No

**Comment by Mustk4824** [comment]
Hi,
****
Can i get the response on this issue, because today it stopped copying files completely to blob storage not even with 20 MB of file size.

Note: Just for information i have clean up all jobs with azcopy jobs clean, which i suppose also clean up the log and plan files. 

This is what i am getting in the STDERR, 

**panic: couldn't create job part plan file "4e8c12ea-ae97-9243-612e-af1d79b0cbea--00000.steV14": open /root/.azcopy/plans/4e8c12ea-ae97-9243-612e-af1d79b0cbea--00000.steV14: no space left on device**

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/ste.JobPartPlanFileName.Create(0xc000752440, 0x32, 0x4e8c12ea00000000, 0x1daf2e619243ae97, 0xeacbb079, 0x103000000000001, 0x1, 0x0, 0x0, 0x0, ...)
        /home/vsts/work/1/s/ste/JobPartPlanFileName.go:131 +0x21d4
github.com/Azure/azure-storage-azcopy/ste.ExecuteNewCopyJobPartOrder(0x4e8c12ea00000000, 0x1daf2e619243ae97, 0xeacbb079, 0x103000000000001, 0x1, 0x0, 0x0, 0x0, 0xc00010c1b0, 0x30, ...)
        /home/vsts/work/1/s/ste/init.go:143 +0xaa
github.com/Azure/azure-storage-azcopy/cmd.inprocSend(0xbe9d44, 0x10, 0xab9e60, 0xc0000d8000, 0xab9ea0, 0xc00000f380, 0x1, 0xc00000f380)
        /home/vsts/work/1/s/cmd/rpc.go:44 +0x965
github.com/Azure/azure-storage-azcopy/cmd.glob..func6(0xbe9d44, 0x10, 0xab9e60, 0xc0000d8000, 0xab9ea0, 0xc00000f380)
        /home/vsts/work/1/s/cmd/rpc.go:36 +0x5d
github.com/Azure/azure-storage-azcopy/cmd.dispatchFinalPart(0xc0000d8000, 0xc00007c700, 0x0, 0x0)
        /home/vsts/work/1/s/cmd/copyEnumeratorHelper.go:62 +0xcf
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).initEnumerator.func6(0xc00000f1e0, 0x0)
        /home/vsts/work/1/s/cmd/copyEnumeratorInit.go:245 +0x33
github.com/Azure/azure-storage-azcopy/cmd.(*copyEnumerator).enumerate(0xc0000b42c0, 0x4e8c12ea00000000, 0x1daf2e619243ae97)
        /home/vsts/work/1/s/cmd/zc_enumerator.go:631 +0x98
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).processCopyJobPartOrders(0xc00007c700, 0x0, 0x0)
        /home/vsts/work/1/s/cmd/copy.go:1100 +0x5da
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).process(0xc00007c700, 0xe8, 0xb)
        /home/vsts/work/1/s/cmd/copy.go:905 +0x84
github.com/Azure/azure-storage-azcopy/cmd.init.2.func2(0xc0001fd400, 0xc0000a52e0, 0x2, 0x2)
        /home/vsts/work/1/s/cmd/copy.go:1475 +0x1de
github.com/spf13/cobra.(*Command).execute(0xc0001fd400, 0xc0000a5240, 0x2, 0x2, 0xc0001fd400, 0xc0000a5240)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x1226160, 0xc000161dd8, 0x0, 0x0)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/Azure/azure-storage-azcopy/cmd.Execute(0xc0000af240, 0xd, 0xc0000af240, 0xd, 0xc0000be920, 0x13, 0xfff)
        /home/vsts/work/1/s/cmd/root.go:140 +0xcf
main.main()
        /home/vsts/work/1/s/main.go:82 +0x3dd

**Comment by Mustk4824** [comment]
I changed the default paths from /root/.azcopy/ to /home/user/, it fixed the issue.
