### ISSUE TITLE
Azcopy "local->Azure Blob" copying a large file (~25 GB) with --block-size-mb leads to errors

### ISSUE THREAD

**Issue by freeriderND** [Azure/azure-storage-azcopy#1642]
### Which version of the AzCopy was used? 
AzCopy 10.13.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Debian GNU/Linux 9 (stretch)

### What command did you run?
azcopy copy "/path/file.tar.bz2" "https://<my_storage_account>.blob.core.windows.net/foto?<SAS>" --overwrite=false --block-size-mb=128

### What problem was encountered?

At first I tried uploading a file with a size of about ~25 GB with `azcopy copy "/path/file.tar.bz2" "https://<my_storage_account>.blob.core.windows.net/foto?<SAS>" --overwrite=false` command. It used 126.9K "PutBlob" and 288.34K "GetBlobProperties" requests :see_no_evil:

Then in order to reduce the number of requests used, I decided to use the parameter `--block-size-mb = 128`:
`azcopy copy "/path/file.tar.bz2" "https://<my_storage_account>.blob.core.windows.net/foto?<SAS>" --overwrite=false --block-size-mb = 128`, but got an error in log file:

```
2021/12/30 08:12:58 ==> REQUEST/RESPONSE (Try=1/245.706Вµs, OpTime=2m9.316776521s) -- REQUEST ERROR
   PUT https://<my_storage_account>.blob.core.windows.net/foto?<SAS>
   Content-Length: [134217728]
   User-Agent: [AzCopy/10.13.0 Azure-Storage/0.14 (go1.16; linux)]
   X-Ms-Client-Request-Id: [1804f6b4-43e6-466e-6693-836d5bbd7945]
   X-Ms-Version: [2019-12-12]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157
HTTP request failed

Put "https://<my_storage_account>.blob.core.windows.net/foto?<SAS>

goroutine 129 [running]:
github.com/Azure/azure-storage-azcopy/v10/ste.stack(0xc0000983f0, 0xc001681100, 0x0)
        /home/vsts/work/1/s/ste/xferLogPolicy.go:237 +0x9f
github.com/Azure/azure-storage-azcopy/v10/ste.NewRequestLogPolicyFactory.func1.1(0x10d2000, 0xc00083c720, 0xc0003e2700, 0x10, 0x2, 0x0, 0xc0003e4b00)
        /home/vsts/work/1/s/ste/xferLogPolicy.go:151 +0x7c5
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000751ae0, 0x10d2000, 0xc00083c720, 0xc0003e2700, 0xc0003e4bb8, 0xb3536d632e041a35, 0x4affca, 0xc000740000)
        /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-azcopy/v10/ste.NewVersionPolicyFactory.func1.1(0x10d2000, 0xc00083c720, 0xc0003e2700, 0x203000, 0x203000, 0x203000, 0x416c3b)
        /home/vsts/work/1/s/ste/mgr-JobPartMgr.go:83 +0x1b4
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0007af530, 0x10d2000, 0xc00083c720, 0xc0003e2700, 0xc000954f38, 0x459799, 0xc009bcc000, 0x37)
        /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-blob-go/azblob.responderPolicy.Do(0x10c2380, 0xc0007af530, 0xc0007782c0, 0x10d2000, 0xc00083c720, 0xc0003e2700, 0x7f546533f3a0, 0x10, 0x10, 0x7f54654ad108)
        /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/zz_generated_responder_policy.go:33 +0x53
github.com/Azure/azure-storage-blob-go/azblob.anonymousCredentialPolicy.Do(...)
        /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/zc_credential_anonymous.go:54
github.com/Azure/azure-storage-azcopy/v10/ste.(*retryNotificationPolicy).Do(0xc00021f160, 0x10d2000, 0xc00083c720, 0xc0003e2700, 0x0, 0xc00083c730, 0xfc3f40, 0xc0009550b8)
        /home/vsts/work/1/s/ste/xferRetryNotificationPolicy.go:59 +0x5b
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc00021f190, 0x10d2000, 0xc00083c720, 0xc0003e2700, 0xc00083c720, 0xc00021f630, 0xc000000001, 0x0)
        /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-azcopy/v10/ste.NewBlobXferRetryPolicyFactory.func1.1(0x10d1f90, 0xc0007920c0, 0xc0003e2600, 0x10, 0xddbb00, 0x64492d747301, 0xc0003e4840)
        /home/vsts/work/1/s/ste/xferRetrypolicy.go:384 +0x74e
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000751b30, 0x10d1f90, 0xc0007920c0, 0xc0003e2600, 0xc0003e4910, 0x203000, 0x203000, 0xc000955448)
        /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.1(0x10d1f90, 0xc0007920c0, 0xc0003e2600, 0x10, 0xddbb00, 0x40fe01, 0xc0003e4840)
        /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/zc_policy_unique_request_id.go:22 +0xd4
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0007af560, 0x10d1f90, 0xc0007920c0, 0xc0003e2600, 0xc0003e48f8, 0x31, 0xc0007a81c0, 0xc000955500)
        /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1(0x10d1f90, 0xc0007920c0, 0xc0003e2600, 0x1, 0x0, 0x1, 0xc0003ce038)
        /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/zc_policy_telemetry.go:34 +0x162
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000229bf0, 0x10d1f90, 0xc0007920c0, 0xc0003e2600, 0xc000229bf0, 0x0, 0xc0009555d0, 0x40fef8)
        /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:43 +0x44
github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc000792080, 0x10d1f90, 0xc0007920c0, 0x10c2480, 0xc0007782c0, 0xc0003e2600, 0x22, 0xc00014e10a, 0xf, 0x0)
        /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/core.go:129 +0x82
github.com/Azure/azure-storage-blob-go/azblob.blockBlobClient.StageBlock(0xc00014e0e0, 0x5, 0x0, 0x0, 0x0, 0xc00014e0e8, 0x22, 0xc00014e10a, 0xf, 0x0, ...)
        /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/zz_generated_block_blob.go:505 +0x505
github.com/Azure/azure-storage-blob-go/azblob.BlockBlobURL.StageBlock(0xc00014e0e0, 0x5, 0x0, 0x0, 0x0, 0xc00014e0e8, 0x22, 0xc00014e10a, 0xf, 0x0, ...)
        /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/url_block_blob.go:96 +0x1f9
github.com/Azure/azure-storage-azcopy/v10/ste.(*blockBlobUploader).generatePutBlock.func1()
        /home/vsts/work/1/s/ste/sender-blockBlobFromLocal.go:78 +0x3e5
github.com/Azure/azure-storage-azcopy/v10/ste.createChunkFunc.func1(0x50)
        /home/vsts/work/1/s/ste/sender.go:180 +0x20e
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).chunkProcessor(0xc000480000, 0x50)
        /home/vsts/work/1/s/ste/JobsAdmin.go:435 +0xd5
created by github.com/Azure/azure-storage-azcopy/v10/ste.(*jobsAdmin).poolSizer
        /home/vsts/work/1/s/ste/JobsAdmin.go:364 +0x66d
```

and these errors keep repeating while the upload is in progress (did not wait for the upload to finish). Changing the `--block-size-mb` value (100/64/32) also leads to errors.

I checked the upload of a smaller file (~256 MB) by the same command and it was **successful** - there were no errors and the file appeared in the storage.

### How can we reproduce the problem in the simplest way?

Try to uploading a file with a size of about ~25 GB with `azcopy copy "/path/file.tar.bz2" "https://<my_storage_account>.blob.core.windows.net/<path>?<SAS>" --overwrite=false --block-size-mb = 128` command

### Have you found a mitigation/solution?
No

**Comment by nakulkar-msft** [comment]
Hi @freeriderND These are n/w errors, benign and will be retried. The errors dont appear if you try this on a stronger network. I'll close this issue. Let us know if transfer fails because of any error.

**Comment by freeriderND** [comment]
How can you explain it?

> I checked the upload of a smaller file (~256 MB) by the same command and it was successful - there were no errors and the file appeared in the storage.

And another question: **will I be forced to pay for all these failed requests?**

**Comment by nakulkar-msft** [comment]
As the number of http requests increase there is a higher probability of them failing. For a 256MB file, the the file gets transferred in fewer requests, and you do not see failures.  Also we are making considerably fewer requests in parallel for a smaller file. 

For pricing considerations, check [here](https://github.com/Azure/azure-storage-azcopy/wiki/Cost-of-data-transfers)

**Comment by freeriderND** [comment]
Did I understand the "--block-size-mb" parameter correctly: it increases the size of the data transmitted within the connection and thereby reduces the number of requests to Azure services, and therefore I pay for fewer requests?
