### ISSUE TITLE
Jobs cleanup results in "panic: <log file> file already closed" 

### ISSUE THREAD

**Issue by webcompas** [Azure/azure-storage-azcopy#1838]
### Which version of the AzCopy was used?
- 10.15.0
- Current dev branch (0e4c1a72129a27d96dac63d2e69abcef1cbfedf8)

### Which platform are you using?
Linux

### What command did you run?
`azcopy jobs clean --with-status=Completed`

### What problem was encountered?
AzCopy exits with return code 2 and prints the following output:
```
panic: close /home/user/.azcopy/70d9d64f-1bc1-0648-47c4-fa15dfe3f44f.log: file already closed

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/v10/common.PanicIfErr(...)
        /tmp/azcopy/common/lifecyleMgr.go:685
github.com/Azure/azure-storage-azcopy/v10/common.(*jobLogger).CloseLog(0xc0004c2000)
        /tmp/azcopy/common/logger.go:168 +0xb6
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobMgr).CloseLog(0xc0002e8700)
        /tmp/azcopy/ste/mgr-JobMgr.go:703 +0x2a
github.com/Azure/azure-storage-azcopy/v10/jobsAdmin.ListJobs(0x64)
        /tmp/azcopy/jobsAdmin/init.go:767 +0x3cd
github.com/Azure/azure-storage-azcopy/v10/cmd.inprocSend({0xe8cdbf, 0x8}, {0xe1bd20, 0x167d340}, {0xcd0fc0, 0xc0004c0300})
        /tmp/azcopy/cmd/rpc.go:50 +0x2b8
github.com/Azure/azure-storage-azcopy/v10/cmd.glob..func7({0xe8cdbf, 0x7ffe3557de0b}, {0xe1bd20, 0x167d340}, {0xcd0fc0, 0xc0004c0300})
        /tmp/azcopy/cmd/rpc.go:36 +0x32
github.com/Azure/azure-storage-azcopy/v10/cmd.handleCleanJobsCommand(0x4)
        /tmp/azcopy/cmd/jobsClean.go:94 +0x86
github.com/Azure/azure-storage-azcopy/v10/cmd.init.6.func2(0xc0004a8c80, {0xc0003eb460, 0x1, 0x1})
        /tmp/azcopy/cmd/jobsClean.go:60 +0xae
github.com/spf13/cobra.(*Command).execute(0xc0004a8c80, {0xc0003eb450, 0x1, 0x1})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x16dfea0)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/Azure/azure-storage-azcopy/v10/cmd.Execute({0xc0000fd7e0, 0xc00009a0e0}, {0xc0000ae870, 0xec7ac3}, 0x74, {0x70d9d64f, 0x1bc1, 0x648, {0x47, 0xc4, ...}})
        /tmp/azcopy/cmd/root.go:189 +0x107
main.main()
        /tmp/azcopy/main.go:88 +0x4b8
```

### How can we reproduce the problem in the simplest way?
1. On a Ubuntu 18.04 system download/build AzCopy.
2. Run some AzCopy jobs (in my case `azcopy sync --delete-destination true $local_path $az_path`)
3. Cleanup jobs using `azcopy jobs clean --with-status=Completed`

### Have you found a mitigation/solution?
No

**Comment by prubis** [comment]
I have this issue too (but on Windows). It looks to me like `azcopy` creates a new logfile for the `jobs clean` job...which it then tries to delete, while it's trying to write to it. 

Note that if I specify `--with-status=Completed` like you, I get the panic s you do. If I don't specify, then it fails for the log file, but doesn't panic.

Example:
```
C:\> (Get-Date).ToUniversalTime()

Thursday, 30 June 2022 5:45:26 AM

C:\> azcopy jobs clean
INFO: Removed 0 files.

Failed to remove log/plan files due to error: remove C:\Users\prubis\.azcopy/d793238a-709b-524b-4425-941a2b43b694.log: The process cannot access the file because it is being used by another process..

C:\> Get-Content C:\Users\prubis\.azcopy/d793238a-709b-524b-4425-941a2b43b694.log
2022/06/30 05:45:28 AzcopyVersion  10.15.0
2022/06/30 05:45:28 OS-Environment  windows
2022/06/30 05:45:28 OS-Architecture  amd64
2022/06/30 05:45:28 Log times are in UTC. Local time is 30 Jun 2022 15:45:28
2022/06/30 05:45:28 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2022-06-30T05:45:23Z or --include-after=2022-06-30T05:45:23Z
C:\>
```

**Comment by nakulkar-msft** [comment]
fixed in Dev
