### ISSUE TITLE
azcopy jobs list fails with panic error to open. access is denied.

### ISSUE THREAD

**Issue by atul-ram** [Azure/azure-storage-azcopy#2017]
##### Note: The version is visible when running AzCopy without any argument
.\azcopy.exe --version 
azcopy version 10.16.2
![image](https://user-images.githubusercontent.com/20022476/211224997-73463b81-3020-4d43-9624-aa2facb5cfe7.png)

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
.\azcopy.exe jobs list 

### What problem was encountered?
panic received while trying to few jobs list .
```
.\azcopy.exe jobs list 

.\azcopy.exe : panic: open C:\AdlsCopy\job-logs/1d209dfa-e557-4148-6fb3-32b0991541ce--00000.steV17: Access is denied.
At line:1 char:1
+ .\azcopy.exe jobs list
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (panic: open C:\...cess is denied.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/v10/common.PanicIfErr(...)
	/home/vsts/work/1/s/common/lifecyleMgr.go:685
github.com/Azure/azure-storage-azcopy/v10/ste.JobPartPlanFileName.Map({0xc000706ec5, 0x32})
	/home/vsts/work/1/s/ste/JobPartPlanFileName.go:65 +0x1d4
github.com/Azure/azure-storage-azcopy/v10/jobsAdmin.(*jobsAdmin).ListJobs(0x1, 0x64)
	/home/vsts/work/1/s/jobsAdmin/JobsAdmin.go:450 +0x173
github.com/Azure/azure-storage-azcopy/v10/jobsAdmin.ListJobs(...)
	/home/vsts/work/1/s/jobsAdmin/init.go:739
github.com/Azure/azure-storage-azcopy/v10/cmd.inprocSend({0xc128c1, 0x8}, {0xba1400, 0x143c9c0}, {0xa55480, 0xc000092840})
	/home/vsts/work/1/s/cmd/rpc.go:50 +0x2c7
github.com/Azure/azure-storage-azcopy/v10/cmd.glob..func6({0xc128c1, 
0xdd6df0}, {0xba1400, 0x143c9c0}, {0xa55480, 0xc000092840})
	/home/vsts/work/1/s/cmd/rpc.go:36 +0x32
github.com/Azure/azure-storage-azcopy/v10/cmd.HandleListJobsCommand(0x4a82ac)
	/home/vsts/work/1/s/cmd/jobsList.go:87 +0x68
github.com/Azure/azure-storage-azcopy/v10/cmd.init.7.func2(0xc0004a2000, {0x150f8e0, 0x0, 0x0})
	/home/vsts/work/1/s/cmd/jobsList.go:67 +0xae
github.com/spf13/cobra.(*Command).execute(0xc0004a2000, {0x150f8e0, 0x0, 0x0})
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x14a96e0)
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/Azure/azure-storage-azcopy/v10/cmd.Execute({0xc0000a0030, 0xc0000780f0}, {0xc0000a0048, 0xc5d53e}, 0x74, {0xe770018b, 0xc4cb, 0x1842, {0x57, 0x3d, ...}})
	/home/vsts/work/1/s/cmd/root.go:189 +0x107
main.main()
	/home/vsts/work/1/s/main.go:88 +0x50f
``` 

### How can we reproduce the problem in the simplest way?

ask a friend to run the azcopy command and generate logs.
then login with another credentials and try to list jobs using command as below 

.\azcopy.exe jobs list 

### Have you found a mitigation/solution?
none , I even tried to add myself to administrator group, but it did not help.

**Comment by adreed-msft** [comment]
Sounds like you don't have permissions to the AzCopy plan file folder. Add yourself to the folder permissions-- Right click the folder, properties, security, and add yourself with read and write permissions.

This is not an AzCopy bug.
