### ISSUE TITLE
10.17.0 copy fails with --include-directory-stub=true

### ISSUE THREAD

**Issue by themorey** [Azure/azure-storage-azcopy#2067]
### Which version of the AzCopy was used? 
10.17.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac and Windows

### What command did you run?
azcopy copy "https://srscwrflustrehsm.blob.core.windows.net/wrfhsm" "https://jmstoragescus.blob.core.windows.net/wrfhsm" --overwrite=prompt --s2s-preserve-access-tier=true --include-directory-stub=true --recursive --log-level=INFO

### What problem was encountered?
The copy started then failed with following message:
```
2.3 %, 188 Done, 0 Failed, 7188 Pending, 0 Skipped, 7376 Total, 2-sec Throughput (Mb/s): 75.7227  panic: folder https://jmstoragescus.blob.core.windows.net/wrfhsm/shared/build/aws/dist/awscli/botocore/data/personalize was not registered when properties persistence occurred

goroutine 7041 [running]:
github.com/Azure/azure-storage-azcopy/v10/ste.(*jpptFolderTracker).ShouldSetProperties(0xc001d640a0, {0xc0017d9f10, 0x69}, 0x2, {0x100c8aa80, 0xc000972000})
	/Users/runner/work/1/s/ste/folderCreationTracker.go:126 +0x2ff
github.com/Azure/azure-storage-azcopy/v10/ste.(*blobFolderSender).EnsureFolderExists(0xc001512400)
	/Users/runner/work/1/s/ste/sender-blobFolders.go:124 +0x2ba
github.com/Azure/azure-storage-azcopy/v10/ste.anyToRemote_folder({_, _}, {{0xa9cefaa2, 0xaf0c, 0xba4c, {0x70, 0x68, 0xa4, 0xdf, 0x43, ...}}, ...}, ...)
	/Users/runner/work/1/s/ste/xfer-anyToRemote-folder.go:70 +0x233
github.com/Azure/azure-storage-azcopy/v10/ste.anyToRemote({0x100c9f8e0, 0xc00111b960}, {0x100c8a7c0, 0xc000f2e100}, {0x135b1d880, 0xc00081a000}, 0xc0026c0e80?, 0x2e?)
	/Users/runner/work/1/s/ste/xfer-anyToRemote-file.go:183 +0x318
github.com/Azure/azure-storage-azcopy/v10/ste.parameterizeSend.func1({0x100c9f8e0?, 0xc00111b960?}, {0x100c8a7c0?, 0xc000f2e100?}, {0x135b1d880?, 0xc00081a000?})
	/Users/runner/work/1/s/ste/xfer.go:77 +0x44
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartMgr).StartJobXfer(0x10129fe60?, {0x100c9f8e0?, 0xc00111b960?})
	/Users/runner/work/1/s/ste/mgr-JobPartMgr.go:720 +0x50
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobPartTransferMgr).StartJobXfer(0xc00111b960?)
	/Users/runner/work/1/s/ste/mgr-JobPartTransferMgr.go:237 +0x32
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobMgr).transferProcessor.func1({0x100c9f8e0, 0xc00111b960})
	/Users/runner/work/1/s/ste/mgr-JobMgr.go:1020 +0x1b9
github.com/Azure/azure-storage-azcopy/v10/ste.(*jobMgr).transferProcessor(0xc000752800, 0x0?)
	/Users/runner/work/1/s/ste/mgr-JobMgr.go:1032 +0xbd
created by github.com/Azure/azure-storage-azcopy/v10/ste.NewJobMgr
	/Users/runner/work/1/s/ste/mgr-JobMgr.go:202 +0xc37
```

### How can we reproduce the problem in the simplest way?
The source blob container has 0B file with metadata including `hdi_isfolder:true` that requires the `--include-directory-stub=true` flag.  This has been replicated on Mac and Windows clients running `10.17.0`.  The same command works with `10.16.2` on both Mac and Windows.

### Have you found a mitigation/solution?
Use `10.16.2` instead

[a9cefaa2-af0c-ba4c-7068-a4df437e1c6b.log](https://github.com/Azure/azure-storage-azcopy/files/10711071/a9cefaa2-af0c-ba4c-7068-a4df437e1c6b.log)

**Comment by themorey** [comment]
I forgot to note that if i run the same azcopy command without `--include-directory-stub=true` using 10.17.0 it does not crash but does not copy the metadata stub files

**Comment by adreed-msft** [comment]
> I forgot to note that if i run the same azcopy command without `--include-directory-stub=true` using 10.17.0 it does not crash (but also does not copy the metadata stub files)

Correct. This appears to be related to the folder persistence manager.

> Use 10.16.2 instead

We made some changes to the way folder persistence works in 10.17.0, so that makes sense why this regression would appear.

**Comment by adreed-msft** [comment]
I'll do some investigation today and try to repro/fix.
