### ISSUE TITLE
azcopy(V10.17.0/V10.18.0) sync crash when there are some read only files in destination folder.

### ISSUE THREAD

**Issue by wingfeng** [Azure/azure-storage-azcopy#2151]
### Which version of the AzCopy was used? 
V10.17.0/V10.18.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Alpine/Windows
### What command did you run?
Job-Command sync https://xxxxxxxx.file.core.windows.net/xxx?se=2023-04-11t05%3A26%3A45z&sharesnapshot=2023-04-10t05%3A26%3A45.0000000z&sig=-REDACTED-&sp=rl&sr=s&sv=2019-07-07 https://xxxxxx.file.core.windows.net/anp?se=2023-04-11t05%3A26%3A46z&sig=-REDACTED-&sp=rcwdl&sr=s&sv=2019-07-07 --preserve-smb-info=true --preserve-smb-permissions=true --recursive=true --log-level=Error --delete-destination=true 

### What problem was encountered?
azcopy crashed with below logs:
Job 62eea6df-8db2-ec46-5303-fa7ea26970dc has started
Log file is located at: d:\azcopy_logs\62eea6df-8db2-ec46-5303-fa7ea26970dc.log

INFO: Deleting extra object: xxxxxxx.zip
INFO: error -> github.com/Azure/azure-storage-file-go/azfile.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-file-go@v0.6.1-0.20201111053559-3c1754dc00a5/azfile/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=ReadOnlyAttribute) =====
Description=The specified resource is read-only and cannot be modified at this time.
RequestId:217fa45c-901a-0081-4c2a-6c5759000000

### How can we reproduce the problem in the simplest way?
mark a file as read-only and start sync job with delete-detination=true
### Have you found a mitigation/solution?
move back to azcopy V10.16.1

**Comment by nakulkar-msft** [comment]
Hi @wingfeng, can you post the backtrace for the crash?

**Comment by wingfeng** [comment]
sorry. Can you told me how to get "backtrace" ?
I have post all message what I can get from screen. 
and here is the 62eea6df-8db2-ec46-5303-fa7ea26970dc.log contents:

2023/04/11 03:56:05 AzcopyVersion  10.18.0
2023/04/11 03:56:05 OS-Environment  windows
2023/04/11 03:56:05 OS-Architecture  amd64
2023/04/11 03:56:05 Log times are in UTC. Local time is 11 Apr 2023 11:56:05 


------------------
it did not closed as wanted.

**Comment by nakulkar-msft** [comment]
If azcopy crashed, it would leave a statement on the cli, with the trace of where it failed. Can you post that? Similar to one below

```

goroutine 7041 [running]:
github.com/Azure/azure-storage-azcopy/v10/ste.(*jpptFolderTracker).ShouldSetProperties(0xc001d640a0, {0xc0017d9f10, 0x69}, 0x2, {0x100c8aa80, 0xc000972000})
	/Users/runner/work/1/s/ste/folderCreationTracker.go:126 +0x2ff
github.com/Azure/azure-storage-azcopy/v10/ste.(*blobFolderSender).EnsureFolderExists(0xc001512400)
	/Users/runner/work/1/s/ste/sender-blobFolders.go:124 +0x2ba
github.com/Azure/azure-storage-azcopy/v10/ste.anyToRemote_folder({_, _}, {{0xa9cefaa2, 0xaf0c, 0xba4c, {0x70, 0x68, 0xa4, 0xdf, 0x43, ...}}, ...}, ...)
----
created by github.com/Azure/azure-storage-azcopy/v10/ste.NewJobMgr
	/Users/runner/work/1/s/ste/mgr-JobMgr.go:202 +0xc37
```

**Comment by wingfeng** [comment]
![azcopy_error](https://user-images.githubusercontent.com/2284132/231127457-8fdab37a-48eb-4147-a39d-1fdc3007b599.png)
here is the screenshot of azcopy running cli. nothing left before I run next command.

**Comment by gapra-msft** [comment]
Hi @wingfeng 

The latest version of AzCopy supports a flag named --force-if-read-only that can be used for situations like this. 

Could you try upgrading, use the new flag and let us know if it resolves your issue?

**Comment by gapra-msft** [comment]
Closing due to inactivity in the thread. Feel free to reopen if you are still experiencing the issue after trying out the above suggestion.
