### ISSUE TITLE
azcopy crashes on Ubuntu / WSL2

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-storage-azcopy#2307]
### Which platform are you using? (ex: Windows, Mac, Linux) 

Windows / WSL2
- Used both the Ubuntu binary and the Windows binary (symlink to /usr/local/bin/azcopy)

### What command did you run?

```bash
azcopy copy "https://prosewaretrainingvideos.blob.core.windows.net/videos/" "https://steapjavarwaXXXXX.file.core.windows.net/trainings/AllTrainings?se=2023-07-21T15%3A44Z&sp=rwdl&spr=https&sv=2022-11-02&sr=s&sig=XXXXX" --recursive=true --as-subdir=false --overwrite=false
```
### What problem was encountered?

Crash:

``` text
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x5f4980]

goroutine 1 [running]:
net/url.(*URL).String(0x0)
        C:/hostedtoolcache/windows/go/1.19.8/x64/src/net/url/url.go:807 +0x40
github.com/Azure/azure-storage-azcopy/v10/cmd.copyHandlerUtil.ConstructCommandStringFromArgs({})
        D:/a/1/s/cmd/copyUtil.go:107 +0x407
github.com/Azure/azure-storage-azcopy/v10/cmd.init.2.func2(0xc000005680?, {0xc0000904b0?, 0x2?, 0x5?})
        D:/a/1/s/cmd/copy.go:1970 +0x1d6
github.com/spf13/cobra.(*Command).execute(0xc000005680, {0xc000090460, 0x5, 0x5})
        C:/Users/VssAdministrator/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x18aa240)
        C:/Users/VssAdministrator/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/VssAdministrator/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/Azure/azure-storage-azcopy/v10/cmd.Execute({0xc000036288?, 0xc0001080e0?}, {0xc000030880?, 0x1027b25?}, 0x74?, {0x12fef878, 0xeb29, 0x8340, {0x7f, 0xd5, ...}})
        D:/a/1/s/cmd/root.go:192 +0x106
main.main()
        D:/a/1/s/main.go:87 +0x52a
```

### How can we reproduce the problem in the simplest way?

The prosewaretrainingvideos share is public.  Run the command on WSL2

### Have you found a mitigation/solution?

No.

**Comment by adrianhall** [comment]
Debugging to find scope - same command also crashes in the same way on MacOS (ARM64), and I downloaded v10.10 - which also crashes the same way.

**Comment by gapra-msft** [comment]
Hi @adrianhall Does the latest version of AzCopy also crash in the same way?

**Comment by adrianhall** [comment]
Sorry @gapra-msft - I cannot test at the moment.  The project moved on by moving away from AzCopy.  Will double check on my own in the next few days.

**Comment by gapra-msft** [comment]
Closing this issue as the panic will no longer occur in latest versions of AzCopy and instead print the appropriate error. Feel free to reopen if you do see an issue after upgrading.
