### ISSUE TITLE
azcopy stuck in long loop when destination cannot be reached, no way to let it fail fast

### ISSUE THREAD

**Issue by BertKoor** [Azure/azure-storage-azcopy#2379]
### Which version of the AzCopy was used? 
AzcopyVersion  10.20.1

### Which platform are you using? (ex: Windows, Mac, Linux)
linux

### What command did you run?
````
azcopy copy myfile.zip https://nonexistant.blob.core.windows.net/dead
````

### What problem was encountered?
When the receiving side of the connection does not exist (or blocks all requests) it takes 15 minutes for azcopy to complete.

Progress indicator of azcopy only shows
````
0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 
````

Snippet from the logfile:
````
023/09/18 09:02:24 PERF: primary performance constraint is Unknown. States: X:  0, O:  0, M:  0, L:  0, R:  0, D:  0, W:  0, F:  0, B:  1, E:  0, T:  1, GRs:  1
2023/09/18 09:02:24 0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total,
2023/09/18 09:02:25 ==> REQUEST/RESPONSE (Try=4/4.855014ms, OpTime=10.373833513s) -- REQUEST ERROR
   PUT https://nonexistant.blob.core.windows.net/dead/myfile.zip?timeout=61
   Authorization: REDACTED
   Content-Length: [2881]
   User-Agent: [AzCopy/10.20.1 Azure-Storage/0.15 (go1.19.12; linux)]
   X-Ms-Blob-Cache-Control: []
   X-Ms-Blob-Content-Disposition: []
   X-Ms-Blob-Content-Encoding: []
   X-Ms-Blob-Content-Language: []
   X-Ms-Blob-Content-Md5: []
   X-Ms-Blob-Content-Type: [application/zip]
   X-Ms-Blob-Type: [BlockBlob]
   X-Ms-Client-Request-Id: [ad7bc8f6-b7ad-403f-6059-a8ecd50b9b3a]
   X-Ms-Version: [2020-10-02]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/error.go:157
HTTP request failed

Put "https://nonexistant.blob.core.windows.net/dead/myfile.zip?timeout=61": dial tcp: lookup nonexistant.blob.core.windows.net on ##.##.##.##:##: no such host

goroutine 114 [running]:
github.com/Azure/azure-storage-azcopy/v10/ste.stack()
        /home/vsts/work/1/s/ste/xferLogPolicy.go:237 +0x65
github.com/Azure/azure-storage-azcopy/v10/ste.NewRequestLogPolicyFactory.func1.1({0x11a69c0, 0xc00050d920}, {0x181dfe0?})
        /home/vsts/work/1/s/ste/xferLogPolicy.go:151 +0xa1c
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000483da0?, {0x11a69c0?, 0xc00050d920?}, {0xc?})
        /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.4-0.20220425205405-09e6f201e1e4/pipeline/core.go:43 +0x2f
github.com/Azure/azure-storage-azcopy/v10/ste.NewBlobPipeline.func1.1({0x11a69c0, 0xc00050d920}, {0xc000326410?})
        /home/vsts/work/1/s/ste/mgr-JobPartMgr.go:201 +0x149
````

### Have you found a mitigation/solution?
No. 

I tried to let it fail faster by setting env.vars AZCOPY_CONCURRENCY_VALUE=1 and AZCOPY_REQUEST_TRY_TIMEOUT=1 and even 0, but that had no effect.

**Comment by gapra-msft** [comment]
Hi @BertKoor Thank you for posting this issue. Here is our recommendation to customers in the past who have hit this issue. https://github.com/Azure/azure-storage-azcopy/issues/1685#issuecomment-1064810441

This behavior is by design, since we don't have a good way to know if the error is transient or fatal. 

Please let us know if you have further questions.

**Comment by BertKoor** [comment]
OK, I understand. You rather have the users of azcopy write more code around it than take responsibility yourself to make it robust to handle anything that can be thrown to it.

For future reference, this is my work-around in linux shell:

````
curl -s https://nonexistant.blob.core.windows.net/dead > /dev/null
if [ $? -ne 0 ] ; then
  echo "endpoint cannot be reached"
  exit 1
fi
azcopy copy myfile.zip https://nonexistant.blob.core.windows.net/dead
````

The `get` by curl actually receives a http status 404-NotFound and a small html body, but it's return code is zero.
In case of real network issues the return code is 6.
