### ISSUE TITLE
Random crash while running "azcopy -v" with 10.22.0 on Azure Batch

### ISSUE THREAD

**Issue by chengjinluo** [Azure/azure-storage-azcopy#2483]
##### Note: The version is visible when running AzCopy without any argument
10.22.0 linux amd64

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux, Ubuntu 22.04

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
`azcopy -v`

### What problem was encountered?

crash with following error

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc97087]

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/v10/common.(*lifecycleMgr).Exit(0xc0003a01b0, 0x0?, 0x0)
	/home/vsts/work/1/s/common/lifecyleMgr.go:375 +0xc7
github.com/Azure/azure-storage-azcopy/v10/cmd.Execute({0xc000044300?, 0x0?}, {0xc000044480?, 0x10eda5c?}, 0x74?, {0x7955fabb, 0x8277, 0xd846, {0x4a, 0xd0, ...}})
	/home/vsts/work/1/s/cmd/root.go:214 +0x182
main.main()
	/home/vsts/work/1/s/main.go:84 +0x507
```

### How can we reproduce the problem in the simplest way?

Start an Azure Batch Job of 16 tasks on a low priority pool with command `bash -c 'wget -q -O azcopy_v10.tar.gz https://aka.ms/downloadazcopy-v10-linux && tar -xf azcopy_v10.tar.gz --strip-components=1 && azcopy -v'`

6 tasks failed in my job

### Have you found a mitigation/solution?

Use old version of azcopy

**Comment by gapra-msft** [comment]
This should be resolved by [this](https://github.com/Azure/azure-storage-azcopy/pull/2484) PR.

**Comment by liushilongbuaa** [comment]
@gapra-msft , how can I download old release?

**Comment by fbreitwieser** [comment]
FYI I've got the same error always and always at the same location in the help page when running `azcopy copy --help` on MacOS w/ v10.22:

```
azcopy copy --help

Copies source data to a destination location. The supported directions are:
  - local <-> Azure Blob (SAS or OAuth authentication)
 ...
Flags Applying to All Commands:
      --cap-mbps float                      Caps the transfer rate, in megabits per second. Moment-by-moment throughput might vary slightly from the cap. If this option is set to zero, or it is omitted, the throughput isn't capped.
      --log-level string                    Define the log verbosity for the log file, available levels: INFO(all requests/responses), WARNING(slow responses), ERROR(only failed requests), and NONE(no output logs). (default 'INFO'). (default "INFO")
      --output-level string                 Define the output verbosity. Available levels: essential, quiet. (default "default")
      --output-type string                  Format of the command's output. The choices include: text, json. The default value is 'text'. (default "text")
      --skip-version-check                  Do not perform the version check at startup. Intended for automation scenarios & airgapped use.
      --trusted-microsoft-suffixes string   Specifies additional domain suffixes where Azure Active Directory login tokens may be sent.  The default is '*.core.windows.net;*.core.chinacloudapi.cn;*.core.cloudapi.de;*.core.usgovcloudapi.net;*.storage.azure.net'. Any listed here are added to the default. For security, you should only put Microsoft Azure domains here. Separate multiple entries with semi-colons.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x102b46bf0]

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/v10/common.(*lifecycleMgr).Exit(0x1400022a990, 0x0?, 0x0)
	github.com/Azure/azure-storage-azcopy/v10/common/lifecyleMgr.go:375 +0xc0
github.com/Azure/azure-storage-azcopy/v10/cmd.Execute({0x1400003b580?, 0x1037817a0?}, {0x1400003eae0?, 0x102cbcc88?}, 0x74?, {0x793190ad, 0xcbc8, 0x3b42, {0x57, 0x1e, ...}})
	github.com/Azure/azure-storage-azcopy/v10/cmd/root.go:214 +0x180
main.main()
	github.com/Azure/azure-storage-azcopy/v10/main.go:84 +0x3a4
```

**Comment by gapra-msft** [comment]
Hi! This has been fixed in our latest release. Please feel free to open a new issue in case you hit any other issues with AzCopy!
