### ISSUE TITLE
azcopy jobs resume fails with "panic" or "sp is mandatory. Cannot be empty"

### ISSUE THREAD

**Issue by faster** [Azure/azure-storage-azcopy#2755]
### Which version of the AzCopy was used? 
10.20.0, 10.22.2, 10.25.1
### Which platform are you using? (ex: Windows, Mac, Linux)
Linux, Mac
### What command did you run?
`azcopy jobs resume 629a9e10-8c12-1a46-4fba-2b3e052e88ac --destination-sas 'https://---'`
### What problem was encountered?
Version 10.20.0 (Rocky Linux aarch64):
```
INFO: Authentication failed, it is either not correct, or expired, or does not have the correct permission -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:2ffe6131-d01e-000a-4b4a-dc8283000000
Time:2024-07-22T15:19:59.4277424Z, Details:
   AuthenticationErrorDetail: sp is mandatory. Cannot be empty
   Code: AuthenticationFailed
   PUT https://---.blob.core.windows.net/setup/test/2024-07-22-11-10-03.mp4?---
   Content-Length: [3441742]
   User-Agent: [AzCopy/10.20.0 Azure-Storage/0.15 (go1.20.2; linux)]
   X-Ms-Blob-Cache-Control: []
   X-Ms-Blob-Content-Disposition: []
   X-Ms-Blob-Content-Encoding: []
   X-Ms-Blob-Content-Language: []
   X-Ms-Blob-Content-Md5: []
   X-Ms-Blob-Content-Type: [video/mp4]
   X-Ms-Blob-Type: [BlockBlob]
   X-Ms-Client-Request-Id: [971efde9-a4ed-477c-7739-cfdd95aced43]
   X-Ms-Version: [2020-10-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Content-Length: [407]
   Content-Type: [application/xml]
   Date: [Mon, 22 Jul 2024 15:19:58 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [2ffe6131-d01e-000a-4b4a-dc8283000000]
```

On version 10.22.2 (mac):
```
RESPONSE 403: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
ERROR CODE: AuthenticationFailed
--------------------------------------------------------------------------------
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:d18aebf1-701e-000c-4434-dc75fb000000
Time:2024-07-22T12:38:44.0000431Z</Message><AuthenticationErrorDetail>sp is mandatory. Cannot be empty</AuthenticationErrorDetail></Error>
--------------------------------------------------------------------------------

INFO: Authentication failed, it is either not correct, or expired, or does not have the correct permission PUT https://---.blob.core.windows.net/setup/resume-test/resume-test/2024-07-11-17-01-00.mp4
--------------------------------------------------------------------------------
RESPONSE 403: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
ERROR CODE: AuthenticationFailed
--------------------------------------------------------------------------------
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:36ca2673-701e-0025-6c34-dc03b9000000
Time:2024-07-22T12:38:43.9981861Z</Message><AuthenticationErrorDetail>sp is mandatory. Cannot be empty</AuthenticationErrorDetail></Error>
```

On version 10.25.1 (mac):
```
panic: runtime error: unsafe.String: len out of range

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/v10/ste.(*JobPartPlanHeader).TransferSrcDstRelatives(0x110c37ae0?, 0x111c67fa?)
	github.com/Azure/azure-storage-azcopy/v10/ste/JobPartPlan.go:155 +0xaa
github.com/Azure/azure-storage-azcopy/v10/ste.(*JobPartPlanHeader).TransferSrcDstStrings(0x1111c6000, 0x0)
	github.com/Azure/azure-storage-azcopy/v10/ste/JobPartPlan.go:169 +0x16c
github.com/Azure/azure-storage-azcopy/v10/jobsAdmin.GetJobFromTo({{0x629a9e10, 0x8c12, 0x1a46, {0x4f, 0xba, 0x2b, 0x3e, 0x5, 0x2e, 0x88, ...}}})
	github.com/Azure/azure-storage-azcopy/v10/jobsAdmin/init.go:724 +0xf0
github.com/Azure/azure-storage-azcopy/v10/cmd.inprocSend({0x1100340e8, 0xc}, {0x1102721c0, 0xc000130690}, {0x110272200, 0xc0004da800})
	github.com/Azure/azure-storage-azcopy/v10/cmd/rpc.go:63 +0x974
github.com/Azure/azure-storage-azcopy/v10/cmd.init.func4({0x1100340e8?, 0xac882e053e2bba4f?}, {0x1102721c0?, 0xc000130690?}, {0x110272200?, 0xc0004da800?})
	github.com/Azure/azure-storage-azcopy/v10/cmd/rpc.go:31 +0x2c
github.com/Azure/azure-storage-azcopy/v10/cmd.resumeCmdArgs.process({{0x7ff7b08c71fb, 0x24}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x7ff7b08c7232, 0xbc}})
	github.com/Azure/azure-storage-azcopy/v10/cmd/jobsResume.go:361 +0x2bc
github.com/Azure/azure-storage-azcopy/v10/cmd.init.9.func2(0xc0004dfb88?, {0xc000112b40?, 0x1?, 0x11002c53a?})
	github.com/Azure/azure-storage-azcopy/v10/cmd/jobsResume.go:221 +0x38
github.com/spf13/cobra.(*Command).execute(0xc0004dfb88, {0xc000112ae0, 0x3, 0x3})
	github.com/spf13/cobra@v1.4.0/command.go:860 +0x684
github.com/spf13/cobra.(*Command).ExecuteC(0x110b73f20)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x38d
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
github.com/Azure/azure-storage-azcopy/v10/cmd.Execute({0xc000040378?, 0x110b5a320?}, {0xc00011e180?, 0xc00019c048?}, 0xc00019c040?, {0xf4cbe6f7, 0x1937, 0x5f42, {0x4f, 0xf5, ...}})
	github.com/Azure/azure-storage-azcopy/v10/cmd/root.go:220 +0xec
main.main()
	github.com/Azure/azure-storage-azcopy/v10/main.go:79 +0x47b
```
### How can we reproduce the problem in the simplest way?
Execute copy command from local device to azure with limited bandwitdth, then cancel it before it finished:
```
azcopy copy --recursive 'resume-test' --cap-mbps 15  'https://---sas'
```
Then try to resume a job by it's id with same SAS:
```
azcopy jobs resume %id% --destination-sas 'https://---sas'
```
### Have you found a mitigation/solution?
Creating SAS not at container level but for whole storage account with `Object` access was able to resume a job.

**Comment by faster** [comment]
Ok my bad, confused **SAS token** with **Blob SAS URL**. Took part after `?` [delimiter](https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview#sas-token) and it worked. 
Still a bit confusing that one can use `copy` command with **Blob SAS URL** but `jobs resume` fails and requires **SAS token**.

**Comment by ashruti-msft** [comment]
Hi, I'm glad your issue was solved. 
You can refer [this document](https://learn.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-jobs-resume?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json) for detailed information of azcopy jobs resume command and other azcopy commands as well. We mainly only need to validate the SAS token for the particular job ID and that's why we have flags for that in our command.
