### ISSUE TITLE
How to disable auto update

### ISSUE THREAD

**Issue by pranereddy** [Azure/azure-storage-azcopy#2797]
##### Note: The version is visible when running AzCopy without any argument
User-Agent: AzCopy/10.21.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux hosted in azure
##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.
azcopy sync 
We are syncing millions of small files around 4TB
### What problem was encountered?
azcopy tries to get metadata from the internet and fails as there is no internet access on the server

`2024/08/28 13:20:20 ==> REQUEST/RESPONSE (Try=1/21.464366ms, OpTime=21.465915ms) -- REQUEST ERROR#012   GET https://azcopyvnextrelease.blob.core.windows.net/releasemetadata/latest_version.txt#012   Accept: application/xml#012   User-Agent: AzCopy/10.21.0 azsdk-go-azblob/v1.1.0 (go1.19.12; linux)#012   X-Ms-Client-Request-Id: ea1b1b8c-8006-4f77-7d42-f4f6ea787e93#012   x-ms-version: #012   --------------------------------------------------------------------------------#012   ERROR:#012Get "https://azcopyvnextrelease.blob.core.windows.net/releasemetadata/latest_version.txt": EOF#012goroutine 53 [running]:#012github.com/Azure/azure-storage-azcopy/v10/ste.stack()#012#011/home/vsts/work/1/s/ste/xferLogPolicy.go:239 +0x65#012github.com/Azure/azure-storage-azcopy/v10/ste.logPolicy.Do({{{0xb2d05e00, 0x0}, 0x109e878, 0xc00040c030}, 0xc0004021e0, 0xc000402210, 0xc000402240}, 0xc000408400)#012#011/home/vsts/work/1/s/ste/xferLogPolicy.go:433 +0xb5d#012github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc0004083c0)#012#011/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.7.1/internal/exported/request.go:84 +0xf8#012github.com/Azure/azure-storage-azcopy/v10/ste.(*trailingDotPolicy).Do(0xf4d340?, 0x181b280?)#012#011/home/vsts/work/1/s/ste/xferVersionPolicy.go:119 +0x225#012github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc000408380)#012#011/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.7.1/internal/exported/request.go:84 +0xf8#012github.com/Azure/azure-storage-azcopy/v10/ste.(*coldTierPolicy).Do(0xc0003ca5e8?, 0xc000408380)#012#011/home/vsts/work/1/s/ste/xferVersionPolicy.go:83 +0xf9#012github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc000408340)#012#011/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.7.1/internal/exported/request.go:84 +0xf8#012github.com/Azure/azure-storage-azcopy/v10/ste.(*versionPolicy).Do(0xc0003ca6c0?, 0xc000408340)#012#011/home/vsts/work/1/s/ste/xferVersionPolicy.go:68 +0x134#012github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc000408300)#012#011/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.7.1/internal/exported/request.go:84 +0xf8#012github.com/Azure/azure-storage-azcopy/v10/ste.(*retryNotificationPolicy).Do(0x0?, 0xc000408300)#012#011/home/vsts/work/1/s/ste/xferRetryNotificationPolicy.go:90 +0x25#012github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc0003ca8c0)#012#011/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.7.1/internal/exported/request.go:84 +0xf8#012github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.(*retryPolicy).Do(0xe12b60?, 0xc000408240)#012#011/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.7.1/runtime/policy_retry.go:134 +0x5b4#012github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc000408200)#012#011/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.7.1/internal/exported/request.go:84 +0xf8#012github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.(*requestIDPolicy).Do(0xc0003caab8?, 0xc000408200)#012#011/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.7.1/runtime/policy_request_id.go:33 +0x146#012github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc0004081c0)#012#011/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.7.1/internal/exported/request.go:84 +0xf8#012github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.telemetryPolicy.Do({{0xc00017c040?, 0xf49980?}}, 0xc0004081c0)#012#011/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.7.1/runtime/policy_telemetry.go:66 +0x1c5#012github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc000408180)#012#011/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.7.1/internal/exported/request.go:84 +0xf8#012github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.includeResponsePolicy(0xc000408180)#012#011/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.7.1/runtime/policy_include_response.go:19 +0x25#012github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.PolicyFunc.Do(0xc000402300?, 0xc0003d0088?)#012#011/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.7.1/internal/exported/request.go:181 +0x1f#012github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc000408140)#012#011/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.7.1/internal/exported/request.go:84 +0xf8#012github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.Pipeline.Do({{0xc000002140?, 0x11e4b88?, 0xc00003c090?}}, 0xc000408140)#012#011/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.7.1/internal/exported/pipeline.go:96 +0x199#012github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/generated.(*BlobClient).Download(_, {_, _}, _, _, _, _)#012#011/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v1.1.0/internal/generated/zz_blob_client.go:878 +0xa8#012github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blob.(*Client).DownloadStream(_, {_, _}, _)#012#011/home/vsts/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v1.1.0/blob/client.go:392 +0x148#012github.com/Azure/azure-storage-azcopy/v10/cmd.beginDetectNewVersion.func1()#012#011/home/vsts/work/1/s/cmd/root.go:262 +0x169#012created by github.com/Azure/azure-storage-azcopy/v10/cmd.beginDetectNewVersion#012#011/home/vsts/work/1/s/cmd/root.go:244 +0x6a`

### Have you found a mitigation/solution?
Disabling auto update of azcopy might fix the issue but there is no official documentation on how to disable the auto update of azcopy.
I came across two variables AZCOPY_DISABLE_AUTO_UPDATE and AZCOPY_AUTO_UPDATE, are these supported.

Best
Reddy

**Comment by tanyasethi-msft** [comment]
Environment Variables - 
You can disable the auto-update feature by setting specific environment variables. The two environment variables you mentioned, AZCOPY_DISABLE_AUTO_UPDATE and AZCOPY_AUTO_UPDATE, are the correct ones to use.

AZCOPY_DISABLE_AUTO_UPDATE: Setting this variable to true disables the auto-update check. This prevents AzCopy from attempting to check for and download the latest version.

AZCOPY_AUTO_UPDATE: Setting this variable to false also prevents AzCopy from auto-updating.

**Memory Utilization Issue**
Regarding the high memory usage (128GB) during the azcopy sync operation, AzCopy is indeed known to consume a large amount of memory when dealing with numerous small files.

AZCOPY_BUFFER_GB: You can control the memory usage by setting the AZCOPY_BUFFER_GB environment variable. This variable limits the amount of memory AzCopy uses for buffering data.

Additionally, you might want to consider splitting the sync operation into smaller chunks or using the --cap-mbps flag to throttle the data transfer rate, which could indirectly reduce memory usage.

**Comment by pranereddy** [comment]
@tanyasethi-msft Thanks for the inputs. I have tried AZCOPY_BUFFER_GB, but it seems to be not working. I kept it to half of the memory but it still consumed almost all the memory most of it is shown as cached memory on the server. 

I will give the speed throttle a try.

Best
Reddy

**Comment by pranereddy** [comment]
@tanyasethi-msft I have checked the both auto update variables AZCOPY_DISABLE_AUTO_UPDATE and AZCOPY_AUTO_UPDATE and they are not working. It is still trying to reach internet to check for latest version.

Since version 10.22.0 cache feature is included, https://github.com/Azure/azure-storage-azcopy/pull/2402. 
So I created a latest_version.txt file under folder .azcopy containing 10.24.0 and a expiry date less than 1 day but it is still going to internet and failing. Is there any way at all to stop the azcopy from going to the internet or atleast do not fail the operation when the internet access is failing.
