### ISSUE TITLE
File storages accounts don't work, Hangs on error

### ISSUE THREAD

**Issue by jacko873** [Azure/azure-storage-azcopy#2837]
### Which version of the AzCopy was used?
10.26.0

### Which platform are you using? (ex: Windows, Mac, Linux)
Linux and Windows

### What command did you run?
```
azcopy list "https://<storage-account-name>.file.core.windows.net/<file-share-name>/?<SAS-token>"
```
```
azcopy copy  "https://<storage-account-name>.blob.core.windows.net/<container-name>/?<SAS-token>"  "https://<storage-account-name>.file.core.windows.net/<file-share-name>/?<SAS-token>" --recursive
```

### What problem was encountered?
CLI Hangs, copy shows no transfer speed and 0%

log file shows peer reset connection 

```
2024/10/18 14:31:23 ==> REQUEST/RESPONSE (Try=1/12.497729ms, OpTime=102.709195ms) -- REQUEST ERROR
   GET https://<storage-account-name>.file.core.windows.net/test/?restype=directory&se=2024-10-19T14%3A27%3A00Z&sig=-REDACTED-&sp=rcwdl&spr=https&sr=s&st=2024-10-18T14%3A27%3A00Z&sv=2022-11-02
   Accept: application/xml
   User-Agent: AzCopy/10.26.0 azsdk-go-azfile/v1.3.0 (go1.22.5; linux)
   X-Ms-Client-Request-Id: 19a1f149-2fef-4474-68e9-03ac809c4291
   x-ms-allow-trailing-dot: true
   x-ms-version: 2023-08-03
   --------------------------------------------------------------------------------
   ERROR:
Get "https://<storage-account-name>.file.core.windows.net/test/?restype=directory&se=2024-10-19T14%3A27%3A00Z&sig=-REDACTED-&sp=rcwdl&spr=https&sr=s&st=2024-10-18T14%3A27%3A00Z&sv=2022-11-02": read tcp SourceIPAddress:55652->storage-accountIPAddress:443: read: connection reset by peer
goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/v10/ste.stack()
	/mnt/vss/_work/1/s/ste/xferLogPolicy.go:100 +0x5e
github.com/Azure/azure-storage-azcopy/v10/ste.logPolicy.Do({{{0xb2d05e00, 0x0}, 0xc00043d800, 0xc00043d818}, 0xc0002e3950, 0xc0002e3980, 0xc0002e39b0}, 0xc0002fc980)
	/mnt/vss/_work/1/s/ste/xferLogPolicy.go:232 +0xaf4
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc0002fc940)
	/home/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.13.0/internal/exported/request.go:144 +0xf0
github.com/Azure/azure-storage-azcopy/v10/ste.(*retryNotificationPolicy).Do(0x0?, 0xc0002fc940)
	/mnt/vss/_work/1/s/ste/xferRetryNotificationPolicy.go:64 +0x2a
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc00053e198)
	/home/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.13.0/internal/exported/request.go:144 +0xf0
github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.(*retryPolicy).Do(0xc00053e3c8?, 0xc0002fc900)
	/home/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.13.0/runtime/policy_retry.go:126 +0x4ee
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc0002fc8c0)
	/home/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.13.0/internal/exported/request.go:144 +0xf0
github.com/Azure/azure-storage-azcopy/v10/ste.(*fileUploadRangeFromURLFixPolicy).Do(0xc00053e448?, 0xc0002fc8c0)
	/mnt/vss/_work/1/s/ste/sender-azureFileFromURL.go:118 +0x165
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc0002fc880)
	/home/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.13.0/internal/exported/request.go:144 +0xf0
github.com/Azure/azure-storage-azcopy/v10/ste.(*versionPolicy).Do(0xc00043d8f0?, 0xc0002fc880)
	/mnt/vss/_work/1/s/ste/xferVersionPolicy.go:49 +0x127
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc0002fc840)
	/home/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.13.0/internal/exported/request.go:144 +0xf0
github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.(*requestIDPolicy).Do(0xc00053e590?, 0xc0002fc840)
	/home/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.13.0/runtime/policy_request_id.go:33 +0x145
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc0002fc800)
	/home/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.13.0/internal/exported/request.go:144 +0xf0
github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.telemetryPolicy.Do({{0xc00040cb00?, 0xc00005e078?}}, 0xc0002fc800)
	/home/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.13.0/runtime/policy_telemetry.go:70 +0x1b4
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc0002fc7c0)
	/home/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.13.0/internal/exported/request.go:144 +0xf0
github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.includeResponsePolicy(0xc0002fc7c0)
	/home/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.13.0/runtime/policy_include_response.go:19 +0x1c
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.PolicyFunc.Do(0x1?, 0xc0002e3da0?)
	/home/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.13.0/internal/exported/request.go:214 +0x19
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.(*Request).Next(0xc0002fc780)
	/home/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.13.0/internal/exported/request.go:144 +0xf0
github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported.Pipeline.Do({{0xc0002f8b40?, 0x12d0600?, 0xc0002e37a0?}}, 0x0?)
	/home/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.13.0/internal/exported/pipeline.go:76 +0x45
github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/internal/generated.(*DirectoryClient).GetProperties(0xc0002e3d40, {0x12d0600?, 0xc0002e37a0?}, 0x0?)
	/home/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azfile@v1.3.0/internal/generated/zz_directory_client.go:349 +0x86
github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/directory.(*Client).GetProperties(0x0?, {0x12d0600?, 0xc0002e37a0?}, 0x0?)
	/home/cloudtest/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azfile@v1.3.0/directory/client.go:215 +0xbb
github.com/Azure/azure-storage-azcopy/v10/cmd.(*fileTraverser).Traverse(0xc0004659f0, 0x0, 0xc0002e6ea0, {0x0, 0x0, 0x0})
	/mnt/vss/_work/1/s/cmd/zc_traverser_file.go:262 +0x64e
github.com/Azure/azure-storage-azcopy/v10/cmd.cookedListCmdArgs.handleListContainerCommand({{0x7ffce47cf10d, 0xbc}, 0x4, {0x1a9c060, 0x0, 0x0}, 0x0, 0x0, 0x0, 0x0})
	/mnt/vss/_work/1/s/cmd/list.go:317 +0x763
github.com/Azure/azure-storage-azcopy/v10/cmd.init.11.func2(0xc00044fb08?, {0xc000449b20?, 0x1?, 0x10f4a2c?})
	/mnt/vss/_work/1/s/cmd/list.go:193 +0xf3
github.com/spf13/cobra.(*Command).execute(0xc00044fb08, {0xc000449af0, 0x1, 0x1})
	/home/cloudtest/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x1a2c280)
	/home/cloudtest/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/cloudtest/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/Azure/azure-storage-azcopy/v10/cmd.Execute({0xc0002f4b00?, 0x1a0fe50?}, {0xc0004161e0?, 0xc000412308?}, 0xc000412300?, {0x4fc1b0f1, 0xe4, 0x484e, {0x6f, 0x41, ...}})
	/mnt/vss/_work/1/s/cmd/root.go:220 +0xec
main.main()
	/mnt/vss/_work/1/s/main.go:79 +0x47b
``` 

Curling commands shows same issues, tested the following 

- Curl Http, and Https
- Public and private endpoints. 
- Newly set up Storage  account with following config
- SAS tokens from both the storage account and file share level

```
#{
    "sku": {
        "name": "Premium_LRS",
        "tier": "Premium"
    },
    "kind": "FileStorage",
    "id": "/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/ResourceGroup/providers/Microsoft.Storage/storageAccounts/storageaccountname",
    "name": "storageaccountname",
    "type": "Microsoft.Storage/storageAccounts",
    "location": "region",
    "tags": {},
    "properties": {
        "dnsEndpointType": "Standard",
        "defaultToOAuthAuthentication": false,
        "publicNetworkAccess": "Enabled",
        "keyCreationTime": {
            "key1": "YYYY-MM-DDTHH:MM:SSZ",
            "key2": "YYYY-MM-DDTHH:MM:SSZ"
        },
        "allowCrossTenantReplication": false,
        "privateEndpointConnections": [],
        "minimumTlsVersion": "TLS1_2",
        "allowBlobPublicAccess": false,
        "allowSharedKeyAccess": true,
        "largeFileSharesState": "Enabled",
        "networkAcls": {
            "bypass": "AzureServices",
            "virtualNetworkRules": [],
            "ipRules": [],
            "defaultAction": "Allow"
        },
        "supportsHttpsTrafficOnly": true,
        "encryption": {
            "requireInfrastructureEncryption": false,
            "services": {
                "file": {
                    "keyType": "Account",
                    "enabled": true,
                    "lastEnabledTime": "YYYY-MM-DDTHH:MM:SSZ"
                },
                "blob": {
                    "keyType": "Account",
                    "enabled": true,
                    "lastEnabledTime": "YYYY-MM-DDTHH:MM:SSZ"
                }
            },
            "keySource": "Microsoft.Storage"
        },
        "provisioningState": "Succeeded",
        "creationTime": "YYYY-MM-DDTHH:MM:SSZ",
        "primaryEndpoints": {
            "file": "https://storageaccountname.file.core.windows.net/"
        },
        "primaryLocation": "region",
        "statusOfPrimary": "available"
    }
}
```
### Few other observations
 - Storage Diagnostic Logs show no logs for the reset commands at all, nothing 
 - Curl commands to look at the shares and properties seems to work fine, but anything against a share itself does not 

### Have you found a mitigation/solution?
Nope :(

**Comment by jacko873** [comment]
Seems to only be a issue with NFS shares

**Comment by jacko873** [comment]
Sooo.. Turns out  FileREST  is only supported on SMB shares, Not NFS, the reporting/ error handling here is poor. but the copy type isn't supported, I would like to recommend that the documentation for AZCOPY should reflect that using Azcopy against NFS shares isn't supported
