### ISSUE TITLE
Non-AWS S3 urls are unsupported

### ISSUE THREAD

**Issue by chris-zenfolio** [Azure/azure-storage-azcopy#2878]
### Which version of the AzCopy was used?
```
$ azcopy --version
azcopy version 10.27.1
```

### Which platform are you using? (ex: Windows, Mac, Linux)
```
$ cat /proc/version
Linux version 6.8.0-1018-azure (buildd@lcy02-amd64-030) (x86_64-linux-gnu-gcc-13 (Ubuntu 13.2.0-23ubuntu4) 13.2.0, GNU ld (GNU Binutils for Ubuntu) 2.42) #21-Ubuntu SMP Fri Nov  8 00:24:36 UTC 2024
```

### What command did you run?
First attempt:
```
$ azcopy copy 'https://s3.wasabisys.com/bucket01' 'https://storage01.blob.core.windows.net/blobcontainer01' --recursive --from-to S3Blob
panic: Invalid S3 URL. AzCopy supports standard virtual-hosted-style or path-style URLs defined by AWS, E.g: https://bucket.s3.amazonaws.com or https://s3.amazonaws.com/bucket

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/v10/common.PanicIfErr(...)
	/mnt/vss/_work/1/s/common/lifecyleMgr.go:724
github.com/Azure/azure-storage-azcopy/v10/common.NewGenericResourceURLParts({{0x7fff9ae0f515, 0x5}, {0x0, 0x0}, 0x0, {0x7fff9ae0f51d, 0x10}, {0x7fff9ae0f52d, 0x22}, {0x0, ...}, ...}, ...)
	/mnt/vss/_work/1/s/common/genericResourceURLParts.go:42 +0x475
github.com/Azure/azure-storage-azcopy/v10/cmd.rawCopyCmdArgs.stripTrailingWildcardOnRemoteSource({{0x7fff9ae0f515, 0x3a}, {0x7fff9ae0f550, 0x4a}, {0x7fff9ae0f5b1, 0x6}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/mnt/vss/_work/1/s/cmd/copy.go:234 +0xc5
github.com/Azure/azure-storage-azcopy/v10/cmd.rawCopyCmdArgs.cook({{0x7fff9ae0f515, 0x3a}, {0x7fff9ae0f550, 0x4a}, {0x7fff9ae0f5b1, 0x6}, {0x0, 0x0}, {0x0, 0x0}, ...})
	/mnt/vss/_work/1/s/cmd/copy.go:296 +0x305
github.com/Azure/azure-storage-azcopy/v10/cmd.init.2.func2(0xc00031c908?, {0xc00031f4a0?, 0x2?, 0x1822c5e?})
	/mnt/vss/_work/1/s/cmd/copy.go:2042 +0x98
github.com/spf13/cobra.(*Command).execute(0xc00031c908, {0xc00031f450, 0x5, 0x5})
	/home/cloudtest/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x2787900)
	/home/cloudtest/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/cloudtest/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/Azure/azure-storage-azcopy/v10/cmd.Execute({0xc000054768?, 0x274b740?}, {0xc0001148c0?, 0xc00009c648?}, 0x411e05?, {0xb008739c, 0xe69f, 0x334d, {0x55, 0x88, ...}})
	/mnt/vss/_work/1/s/cmd/root.go:233 +0xec
main.main()
	/mnt/vss/_work/1/s/main.go:79 +0x47b
```
Second attempt:
```
$ azcopy copy 'https://bucket01.s3.wasabisys.com' 'https://storage01.blob.core.windows.net/blobcontainer01' --recursive --from-to S3Blob
panic: Invalid S3 URL. AzCopy supports standard virtual-hosted-style or path-style URLs defined by AWS, E.g: https://bucket.s3.amazonaws.com or https://s3.amazonaws.com/bucket

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/v10/common.PanicIfErr(...)
	/mnt/vss/_work/1/s/common/lifecyleMgr.go:724
github.com/Azure/azure-storage-azcopy/v10/common.NewGenericResourceURLParts({{0x7ffd32f0d515, 0x5}, {0x0, 0x0}, 0x0, {0x7ffd32f0d51d, 0x32}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
	/mnt/vss/_work/1/s/common/genericResourceURLParts.go:42 +0x475
github.com/Azure/azure-storage-azcopy/v10/cmd.rawCopyCmdArgs.stripTrailingWildcardOnRemoteSource({{0x7ffd32f0d515, 0x3a}, {0x7ffd32f0d550, 0x4a}, {0x7ffd32f0d5b1, 0x6}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/mnt/vss/_work/1/s/cmd/copy.go:234 +0xc5
github.com/Azure/azure-storage-azcopy/v10/cmd.rawCopyCmdArgs.cook({{0x7ffd32f0d515, 0x3a}, {0x7ffd32f0d550, 0x4a}, {0x7ffd32f0d5b1, 0x6}, {0x0, 0x0}, {0x0, 0x0}, ...})
	/mnt/vss/_work/1/s/cmd/copy.go:296 +0x305
github.com/Azure/azure-storage-azcopy/v10/cmd.init.2.func2(0xc0002ac908?, {0xc0002c0cd0?, 0x2?, 0x1822c5e?})
	/mnt/vss/_work/1/s/cmd/copy.go:2042 +0x98
github.com/spf13/cobra.(*Command).execute(0xc0002ac908, {0xc0002c0c80, 0x5, 0x5})
	/home/cloudtest/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x2787900)
	/home/cloudtest/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/cloudtest/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/Azure/azure-storage-azcopy/v10/cmd.Execute({0xc0004a8630?, 0x274b740?}, {0xc0004807c0?, 0xc00009c648?}, 0x411e05?, {0x6998a738, 0x32cc, 0xb04d, {0x4e, 0xb2, ...}})
	/mnt/vss/_work/1/s/cmd/root.go:233 +0xec
main.main()
	/mnt/vss/_work/1/s/main.go:79 +0x47b
```

### What problem was encountered?
Non-AWS S3 endpoints are unsupported, even if fully-compliant with S3 standards.  _See output above._

### How can we reproduce the problem in the simplest way?
Use azcopy with any non-AWS S3 provider (Wasabi, IBM, Backblaze, etc). [Link to rclone's supported S3 providers for reference](https://rclone.org/s3/)

### Have you found a mitigation/solution?
I do not have a solution other than to not use azcopy, and I would prefer to leverage azcopy since we are migrating storage into Azure from the other providers

**Comment by xrimpy** [comment]
Rclone it.

**Comment by chris-zenfolio** [comment]
That would be nice, but rclone's backend code does not support copying
metadata into Azure Files and Azure Blob Storage.  We need that metadata.

https://forum.rclone.org/t/rclone-user-metadata-and-azureblob/40576/5
and
https://rclone.org/overview/#features
