### ISSUE TITLE
azcopy 10.0.9 fails with setaccessblobtier not supported

### ISSUE THREAD

**Issue by frejsoya** [Azure/azure-storage-azcopy#327]
This works without issues in 10.0.8

### Which version of the AzCopy was used? 
10.0.9 (works in 10.0.8)

### Which platform are you using? (ex: Windows, Mac, Linux)
linux

### What problem was encountered?
Failed to copy blob. 

### Have you found a mitigation/solution?
Use a hardcoded link to 10.0.8

```
2019/04/09 08:27:30 AzcopyVersion  10.0.9-Preview
2019/04/09 08:27:30 OS-Environment  linux
2019/04/09 08:27:30 OS-Architecture  amd64
2019/04/09 08:27:31 ==> REQUEST/RESPONSE (Try=1/25.0545ms, OpTime=25.1449ms) -- RESPONSE STATUS CODE ERROR
   PUT https://abaazewpmlitzzzzzzzzz001.blob.core.windows.net/aaforecast/UDF_Booking_Pippi.txt.gz?comp=tier&se=2021-07-06t16%3A25%3A35z&sig=REDACTED&sp=rwdc&spr=https%2Chttp&srt=o&ss=b&st=2019-03-22t09%3A25%3A35z&sv=2018-03-28&timeout=901
   User-Agent: [AzCopy/10.0.9-Preview Azure-Storage/0.6 (go1.10.3; linux)]
   X-Ms-Access-Tier: [Hot]
   X-Ms-Client-Request-Id: [b23e5236-64e9-4e03-7dd4-2bd57afebc82]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 Blob access tier is not supported on this storage account type.
   Content-Length: [272]
   Content-Type: [application/xml]
   Date: [Tue, 09 Apr 2019 08:27:30 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [BlobAccessTierNotSupportedForAccountType]
   X-Ms-Request-Id: [ce9a4434-c01e-0045-01ae-ee673c000000]
   X-Ms-Version: [2018-11-09]
goroutine 29 [running]:
github.com/Azure/azure-storage-azcopy/ste.stack(0xc420172a80, 0xc420eb0400, 0xc4209d0ab0)
    /go/src/github.com/Azure/azure-storage-azcopy/ste/xferLogPolicy.go:135 +0xa7
github.com/Azure/azure-storage-azcopy/ste.NewRequestLogPolicyFactory.func1.1(0xc81640, 0xc420e9cd80, 0xc420b34c00, 0xbe2c9a, 0xc, 0xbe11df, 0xa)
    /go/src/github.com/Azure/azure-storage-azcopy/ste/xferLogPolicy.go:102 +0x665
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc4209c3c70, 0xc81640, 0xc420e9cd80, 0xc420b34c00, 0xa, 0xc42018a000, 0x7fe29a6c74e8, 0x201)
    /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x44
github.com/Azure/azure-storage-azcopy/ste.NewVersionPolicyFactory.func1.1(0xc81640, 0xc420e9cd80, 0xc420b34c00, 0x7fe29c7016c8, 0x0, 0xc420b2ee58, 0x42b394)
    /go/src/github.com/Azure/azure-storage-azcopy/ste/mgr-JobPartMgr.go:68 +0xe8
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc4209c8ba0, 0xc81640, 0xc420e9cd80, 0xc420b34c00, 0xc420b2ef50, 0x10, 0xc420b2ee98, 0xc420b2ef00)
    /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x44
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.responderPolicy.Do(0xc7a640, 0xc4209c8ba0, 0xc420906000, 0xc81640, 0xc420e9cd80, 0xc420b34c00, 0x10, 0x10, 0xb16140, 0xc420041000)
    /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zz_generated_responder_policy.go:34 +0x53
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.anonymousCredentialPolicy.Do(0xc7a680, 0xc4209c8bc0, 0xc81640, 0xc420e9cd80, 0xc420b34c00, 0x77b38e199401, 0xc420b2ef70, 0xc420b2f030, 0x4cfba3)
    /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_credential_anonymous.go:54 +0x4f
github.com/Azure/azure-storage-azcopy/ste.(*retryNotificationPolicy).Do(0xc4209e17e0, 0xc81640, 0xc420e9cd80, 0xc420b34c00, 0x0, 0x0, 0x0, 0xc420b2f080)
    /go/src/github.com/Azure/azure-storage-azcopy/ste/xferRetryNotificationPolicy.go:59 +0x5e
github.com/Azure/azure-storage-azcopy/ste.(*retryNotificationPolicy).Do-fm(0xc81640, 0xc420e9cd80, 0xc420b34c00, 0x10c04c0, 0xc81640, 0xc420e9cd80, 0xc4209e19d0)
    /go/src/github.com/Azure/azure-storage-azcopy/ste/xferRetryNotificationPolicy.go:77 +0x48
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc4209e1800, 0xc81640, 0xc420e9cd80, 0xc420b34c00, 0xc420e9cd80, 0xc4209e19d0, 0x1, 0x0)
    /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x44
github.com/Azure/azure-storage-azcopy/ste.NewBlobXferRetryPolicyFactory.func1.1(0xc81680, 0xc42018c9f0, 0xc420b34b00, 0xbe9a7c, 0x16, 0xc420e48660, 0x24)
    /go/src/github.com/Azure/azure-storage-azcopy/ste/xferRetrypolicy.go:365 +0x716
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc4209c3cc0, 0xc81680, 0xc42018c9f0, 0xc420b34b00, 0x24, 0x5f6680, 0xb46980, 0xc42018ca20)
    /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x44
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.1(0xc81680, 0xc42018c9f0, 0xc420b34b00, 0xbe14eb, 0xa, 0xc420175300, 0x39)
    /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_policy_unique_request_id.go:19 +0x9c
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc4209c8be0, 0xc81680, 0xc42018c9f0, 0xc420b34b00, 0x39, 0xc42000e278, 0xc42018ca80, 0xc420b2f450)
    /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x44
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1(0xc81680, 0xc42018c9f0, 0xc420b34b00, 0x1, 0x0, 0x1, 0xc42000e278)
    /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_policy_telemetry.go:34 +0x9e
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc42018ca80, 0xc81680, 0xc42018c9f0, 0xc420b34b00, 0xc42018ca80, 0x0, 0xc420b2f4c0, 0x412618)
    /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x44
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc4208e4d00, 0xc81680, 0xc42018c9f0, 0xc7a6a0, 0xc420906000, 0xc420b34b00, 0x2e, 0xc42000ab36, 0x24, 0x0)
    /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:128 +0x81
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.blobClient.SetTier(0xc42000ab00, 0x5, 0x0, 0x0, 0x0, 0xc42000ab08, 0x2e, 0xc42000ab36, 0x24, 0x0, ...)
    /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/zz_generated_blob.go:1065 +0x38a
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob.BlobURL.SetTier(0xc42000ab00, 0x5, 0x0, 0x0, 0x0, 0xc42000ab08, 0x2e, 0xc42000ab36, 0x24, 0x0, ...)
    /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/azblob/url_blob.go:106 +0xd6
github.com/Azure/azure-storage-azcopy/ste.(*blockBlobSenderBase).Epilogue(0xc4200d7900)
    /go/src/github.com/Azure/azure-storage-azcopy/ste/sender-blockBlob.go:150 +0x351
github.com/Azure/azure-storage-azcopy/ste.epilogueWithCleanupSendToRemote(0xc91c40, 0xc420099e50, 0x7fe29a6ce4c8, 0xc4200d7900, 0xc7f1c0, 0xc4209d29a0)
    /go/src/github.com/Azure/azure-storage-azcopy/ste/xfer-anyToRemote.go:291 +0x90
github.com/Azure/azure-storage-azcopy/ste.anyToRemote.func2()
    /go/src/github.com/Azure/azure-storage-azcopy/ste/xfer-anyToRemote.go:142 +0x57
github.com/Azure/azure-storage-azcopy/ste.(*jobPartTransferMgr).runActionAfterLastChunk(0xc420099e50)
    /go/src/github.com/Azure/azure-storage-azcopy/ste/mgr-JobPartTransferMgr.go:334 +0x42
github.com/Azure/azure-storage-azcopy/ste.(*jobPartTransferMgr).ReportChunkDone(0xc420099e50, 0xc4205c6b40, 0xee, 0x2000000, 0xc420e1f438, 0xc420e1f43c, 0x10c4a40)
    /go/src/github.com/Azure/azure-storage-azcopy/ste/mgr-JobPartTransferMgr.go:317 +0x8a
github.com/Azure/azure-storage-azcopy/ste.createChunkFunc.func1(0x0)
    /go/src/github.com/Azure/azure-storage-azcopy/ste/sender.go:149 +0x131
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).chunkProcessor(0xc4201381e0, 0x0)
    /go/src/github.com/Azure/azure-storage-azcopy/ste/JobsAdmin.go:230 +0x90
created by github.com/Azure/azure-storage-azcopy/ste.initJobsAdmin
    /go/src/github.com/Azure/azure-storage-azcopy/ste/JobsAdmin.go:181 +0x697
2019/04/09 08:27:31 ERR: [P#0-T#0] COPYFAILED: https://fpo.blob.core.windows.net/demand-flow/volume-pre/master/batch/2019-04-08/1554701116.csv.gz?se=2020-01-15t00%3A00%3A00z&sig=REDACTED&sp=rl&sr=c&st=2019-03-18t09%3A53%3A52z&sv=2018-03-28 : 400 : 400 Blob access tier is not supported on this storage account type.. When Setting BlockBlob tier. X-Ms-Request-Id: ce9a4434-c01e-0045-01ae-ee673c000000
   Dst: https://abaazewpmlitzzzzzzzzz001.blob.core.windows.net/aaforecast/UDF_Booking_Pippi.txt.gz?se=2021-07-06t16%3A25%3A35z&sig=REDACTED&sp=rwdc&spr=https%2Chttp&srt=o&ss=b&st=2019-03-22t09%3A25%3A35z&sv=2018-03-28
```

**Comment by frejsoya** [comment]
Also, there is no public link to the v10.0.8 binary, so we had to guess where it was based on the v10.0.9 link. We were using the aka.ms/ shorthand link.

**Comment by seguler** [comment]
Have you used the exact same account in v10.0.8 ? The issue doesn't seem to be with AzCopy. Service is telling you that it does not support Blob tiers.

**Comment by frejsoya** [comment]
Yep. It worked again when we downgraded. Docker, production setup. We are
supposedly not actively trying to set a blob tier as well. Just copy.

**Comment by seguler** [comment]
Thanks for clarifying. We're looking into it.

**Comment by zezha-msft** [comment]
Hi @frejsoya, thanks for reaching out!

In 10.0.9, we added the feature to automatically replicate the source blob's tier info to the destination. If you are using an account type that does not support tiers, please use the flag `--s2s-preserve-access-tier=false` to turn it off.

**Comment by frejsoya** [comment]
Thanks, I can’t tell if the default change makes sense :)
The storage account is supposedly GP v2.

**Comment by zezha-msft** [comment]
@frejsoya I agree, I'll bring it with the Team and see if we should change the default behavior. We appreciate your feedback! Thanks!
