### ISSUE TITLE
Upload file error with azcopy10.3.3

### ISSUE THREAD

**Issue by xuetao8997** [Azure/azure-storage-azcopy#800]
### Which platform are you using? (ex: Windows, Mac, Linux)
Windows
### What problem was encountered?
panic: runtime error: invalid memory address or nil pointer dereference
At line:1 char:1
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x9b2e52]
goroutine 53 [running]:
github.com/Azure/azure-storage-azcopy/ste.ErrorEx.ErrorCodeAndString
(0x0, 0x0, 0x0, 0xc0873d11e0, 0x188, 0xc0011e7a28, 0x9cb80d)
       /home/vsts/work/1/s/ste/ErrorExt.go:25 +0x42
github.com/Azure/azure-storage-azcopy/ste.(*jobPartTransferMgr).failActiveTransfer(0xc0035bd9e0, 0xbb101a, 0xc, 0xbb2b04, 0xf, 0x0, 0x0

0xffffffff)
       /home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:626 +0x9b
github.com/Azure/azure-storage-azcopy/ste.(*jobPartTransferMgr).FailActiveUpload(...)
       /home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:559
github.com/Azure/azure-storage-azcopy/ste.(*jobPartTransferMgr).FailActiveSend(
0xc0035bd9e0, 0xbb2b04, 0xf
, 0x0, 
0x0)
       
/home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:596
+0xfe
github.com/Azure/azure-storage-azcopy/ste.scheduleSendChunks.func1
()
       /home/vsts/work/1/s/ste/xfer-anyToRemote.go:264 +0x63
github.com/Azure/azure-storage-azcopy/ste.createChunkFunc.func1(0x1)
       /home/vsts/work/1/s/ste/sender.go:165 +0x1ae
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).chunkProcessor(0xc0002161a0, 0x1)
       /home/vsts/work/1/s/ste/JobsAdmin.go:427 +0xe6
created by github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).poolSizer
       /home/vsts/work/1/s/ste/JobsAdmin.go:356
0x682 

### How can we reproduce the problem in the simplest way?
re-run the command
### Have you found a mitigation/solution?
Not yet

**Comment by xuetao8997** [comment]
#### Here's the new error information:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x9b2e52]

goroutine 135 [running]:
github.com/Azure/azure-storage-azcopy/ste.ErrorEx.ErrorCodeAndString(0x0, 0x0, 0x0, 0xc085d22600, 0x17e, 0xc000a45a28, 0x9cb80d)
        /home/vsts/work/1/s/ste/ErrorExt.go:25 +0x42
github.com/Azure/azure-storage-azcopy/ste.(*jobPartTransferMgr).failActiveTransfer(0xc001ac1800, 0xbb101a, 0xc, 0xbb2b04, 0xf, 0x0, 0x0, 0xffffffff)
        /home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:626 +0x9b
github.com/Azure/azure-storage-azcopy/ste.(*jobPartTransferMgr).FailActiveUpload(...)
        /home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:559
github.com/Azure/azure-storage-azcopy/ste.(*jobPartTransferMgr).FailActiveSend(0xc001ac1800, 0xbb2b04, 0xf, 0x0, 0x0)
        /home/vsts/work/1/s/ste/mgr-JobPartTransferMgr.go:596 +0xfe
github.com/Azure/azure-storage-azcopy/ste.scheduleSendChunks.func1()
        /home/vsts/work/1/s/ste/xfer-anyToRemote.go:264 +0x63
github.com/Azure/azure-storage-azcopy/ste.createChunkFunc.func1(0x13)
        /home/vsts/work/1/s/ste/sender.go:165 +0x1ae
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).chunkProcessor(0xc00005e000, 0x13)
        /home/vsts/work/1/s/ste/JobsAdmin.go:427 +0xe6
created by github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).poolSizer
        /home/vsts/work/1/s/ste/JobsAdmin.go:356 +0x682

**Comment by xuetao8997** [comment]
@JohnRusk Thank you!
