### ISSUE TITLE
Transfer of .pst file to Office 365 cannot complete with AzCopy for mac

### ISSUE THREAD

**Issue by epgui** [Azure/azure-storage-azcopy#87]
##### Note: The version is visible when running AzCopy without any argument

- AzCopy 10.0.2-Preview

### Which platform are you using? (ex: Windows, Mac, Linux)

- macOS High Sierra, 10.13.6 (17G65)

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

- The following command was run, with URL parameters and file paths replaced by underscores for privacy and security reasons:

```
./azcopy cp "___/backup.pst" "https://___.blob.core.windows.net/ingestiondata?sv=___&sr=___&si=___&sig=___&se=___"
```

Note that the [instructions for Windows](https://docs.microsoft.com/en-us/office365/securitycompliance/use-network-upload-to-import-pst-files) specify the following command:

```
AzCopy.exe /Source:<Location of PST files> /Dest:<SAS URL> /V:<Log file location> /Y
```

with the following comment regarding `/Y`:

> This required switch allows the use of write-only SAS tokens when you upload the PST files to the Azure storage location. The SAS URL you obtained in step 1 (and specified in /Dest: parameter) is a write-only SAS URL, which is why you must include this switch. Note that a write-only SAS URL will not prevent you from using the Azure Storage Explorer to view a list of the PST files uploaded to the Azure storage location.

I am unsure how to add the equivalent tag here, as I have found no pointers in the documentation or help pages.

### What problem was encountered?

- AzCopy ran silently for a very long time and ended with a failed transfer:

```
Job a0eef242-719d-c04f-4cd7-8765dcf1b232 has started

a0eef242-719d-c04f-4cd7-8765dcf1b232.log file created in /___/.azcopy
0 Done, 1 Failed, 0 Pending, 0 Skipped, 1 Total
```

In the log file I have the following header:

```
2018/10/12 03:31:09 AzcopVersion  10.0.2-Preview
2018/10/12 03:31:09 OS-Environment  darwin
2018/10/12 03:31:09 OS-Architecture  amd64
2018/10/12 03:31:09 Job-Command cp ___/backup.pst https://___.blob.core.windows.net/ingestiondata?se=___&si=___&sig=___&sr=___&sv=___
2018/10/12 03:31:09 JobID=dfb0ba05-f63c-5748-62e2-8b5f5aa5745a, credential type: Anonymous
2018/10/12 03:31:09 scheduling JobID=dfb0ba05-f63c-5748-62e2-8b5f5aa5745a, Part#=0, Transfer#=0, priority=0
2018/10/12 03:31:09 INFO: [P#0-T#0] has worker 213 which is processing TRANSFER
2018/10/12 03:31:09 INFO: [P#0-T#0] Starting transfer: Source "___/backup.pst" Destination "https://___.blob.core.windows.net/ingestiondata/backup.pst?se=___&si=___&sig=___&sr=___&sv=___". Specified chunk size 8388608
```

Followed by a BUNCH of these that all have the exact same timestamp and "try" number (Try=1):

```
2018/10/12 03:31:09 ==> OUTGOING REQUEST (Try=1)
PUT https://___.blob.core.windows.net/ingestiondata/backup.pst?blockid=___&comp=___&se=___&si=___&sig=___&sr=___&sv=___&timeout=901
Content-Length: [8388608]
User-Agent: [AzCopy/v10.0.2-Preview Azure-Storage/0.1 (go1.10.3; darwin)]
X-Ms-Client-Request-Id: [7cb4a66d-c7d6-4b5e-7d91-6557c2855b95]
X-Ms-Version: [2018-03-28]
```

And then a bunch of these (whitespace may be wonky, as I have trouble copying from vim):

```
2018/10/12 03:35:27 ==> REQUEST/RESPONSE (Try=1/4m17.34582974s[SLOW >3s], OpTime=4m17.345889972s) -- REQUEST ERROR
    PUT https://___.blob.core.windows.net/ingestiondata/backup.pst?blockid=___&comp=___&se=___&si=___&sig=___&sr=___&sv=___&timeout=901
    Content-Length: [8388608]
    User-Agent: [AzCopy/v10.0.2-Preview Azure-Storage/0.1 (go1.10.3; darwin)]
    X-Ms-Client-Request-Id: [1db006dc-c187-4242-6a08-d290227a7d60]
    X-Ms-Version: [2018-03-28]
    --------------------------------------------------------------------------------
    ERROR:
-> github.com/Azure/azure-storage-azcopy/ste.newAzcopyHTTPClientFactory.func1.1, /go/src/github.com/Azure/azure-storage-azcopy/ste/mgr-JobPartMgr.go:95
 HTTP request failed
 
Put https://___.blob.core.windows.net/ingestiondata/backup.pst?blockid=___&comp=___&se=___&si=___&sig=___&sr=___&sv=___&timeout=901: read tcp 10.254.246.200:52028->52.239.148.74:443: read: connection reset by peer

goroutine 264 [running]:
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob.stack(0xc42014e310, 0xc420a52100, 0x0)
         /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob/zc_policy_request_log.go:146 +0xa7
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob.NewRequestLogPolicyFactory.func1.1(0x461c020, 0xc4209828a0, 0xc420996800, 0x45b502b, 0xc, 0x45      b4175, 0xa)
         /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob/zc_policy_request_log.go:96 +0x665
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc42096c8c0, 0x461c020, 0xc4209828a0, 0xc420996800, 0xa, 0x452fa80, 0xc420044800, 0xc42072f8      d0)
         /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x44
github.com/Azure/azure-storage-azcopy/ste.NewVersionPolicyFactory.func1.1(0x461c020, 0xc4209828a0, 0xc420996800, 0x0, 0xc4209b7118, 0x402bcd4, 0x45d5b90)
         /go/src/github.com/Azure/azure-storage-azcopy/ste/mgr-JobPartMgr.go:59 +0xe8
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc4209053a0, 0x461c020, 0xc4209828a0, 0xc420996800, 0xc4209b7128, 0xc4209b71e8, 0x4119083, 0      xc4209828b0)
         /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x44
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob.responderPolicy.Do(0x46186a0, 0xc4209053a0, 0xc420744d20, 0x461c020, 0xc4209828a0, 0xc42099680      0, 0xc4209828b0, 0x461bfa0, 0xc42072f8c0, 0x0)
         /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob/zz_generated_responder_policy.go:33 +0x53
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob.anonymousCredentialPolicy.Do(0x46186e0, 0xc4209053c0, 0x461c020, 0xc4209828a0, 0xc420996800, 0      x4913da0, 0x461c020, 0xc4209828a0, 0xc420953660)
         /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob/zc_credential_anonymous.go:54 +0x4f
github.com/Azure/azure-storage-azcopy/ste.NewBlobXferRetryPolicyFactory.func1.1(0x461bfa0, 0xc42072f8c0, 0xc420996700, 0x45b9940, 0x16, 0xc4208d39b0, 0x24)
         /go/src/github.com/Azure/azure-storage-azcopy/ste/xfer-retrypolicy.go:362 +0x6c1
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc42096c910, 0x461bfa0, 0xc42072f8c0, 0xc420996700, 0x24, 0x41f7870, 0x454f900, 0xc4208ef6b0      )
         /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x44
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob.NewUniqueRequestIDPolicyFactory.func1.1(0x461bfa0, 0xc42072f8c0, 0xc420996700, 0x45b432d, 0xa,       0xc420768180, 0x3b)
         /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob/zc_policy_unique_request_id.go:19 +0x9c
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc4209053e0, 0x461bfa0, 0xc42072f8c0, 0xc420996700, 0x3b, 0xc42000e450, 0xc4208ef710, 0xc420      9b7608)
         /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x44
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob.NewTelemetryPolicyFactory.func1.1(0x461bfa0, 0xc42072f8c0, 0xc420996700, 0x1, 0x0, 0x1, 0xc420      00e450)
        /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob/zc_policy_telemetry.go:34 +0x9e
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc4208ef710, 0x461bfa0, 0xc42072f8c0, 0xc420996700, 0xc4208ef710, 0x45b24df, 0xc4209b7678, 0      x4013318)
         /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:42 +0x44
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc42072f880, 0x461bfa0, 0xc42072f8c0, 0x4618700, 0xc420744d20, 0xc420996700, 0x2d, 0xc42079      2035, 0x19, 0x0)
         /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-pipeline-go/pipeline/core.go:128 +0x81
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob.blockBlobClient.StageBlock(0xc420792000, 0x5, 0x0, 0x0, 0x0, 0xc420792008, 0x2d, 0xc420792035,       0x19, 0x0, ...)
         /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob/zz_generated_block_blob.go:262 +0x4a9
github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob.BlockBlobURL.StageBlock(0xc420792000, 0x5, 0x0, 0x0, 0x0, 0xc420792008, 0x2d, 0xc420792035, 0x      19, 0x0, ...)
         /go/src/github.com/Azure/azure-storage-azcopy/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob/url_block_blob.go:74 +0x131
github.com/Azure/azure-storage-azcopy/ste.(*blockBlobUpload).blockBlobUploadFunc.func1(0xdf)
         /go/src/github.com/Azure/azure-storage-azcopy/ste/xfer-localToBlockBlob.go:338 +0x5a1
github.com/Azure/azure-storage-azcopy/ste.(*jobsAdmin).transferAndChunkProcessor(0xc4201340c0, 0xdf)
         /go/src/github.com/Azure/azure-storage-azcopy/ste/JobsAdmin.go:216 +0xa6
created by github.com/Azure/azure-storage-azcopy/ste.initJobsAdmin
         /go/src/github.com/Azure/azure-storage-azcopy/ste/JobsAdmin.go:160 +0x501
```

... but yeah, it's a >12MB log file. Is it safe to share all its contents? I can't tell what's sensitive and what's not haha.

### How can we reproduce the problem in the simplest way?

- Follow these instructions to migrate old emails backed up into a .pst file into a new Office 365 email server: https://docs.microsoft.com/en-us/office365/securitycompliance/use-network-upload-to-import-pst-files

### Have you found a mitigation/solution?

- Not yet... I am trying to find a Windows PC I can borrow to try getting it done with the Windows utility. This is rather frustrating. I really appreciate any insights or advice you may have! Thanks for taking the time to read this.

**Comment by epgui** [comment]
This exact issue has been replicated on Windows 10, using AzCopy 10.0.2-Preview as well, with a friend's computer.

**Comment by seguler** [comment]
Do you mind retrying again after reducing the number of parallel connections ? It seems you got a TCP failure, and I wonder if it is something to do with too many connections.

Set the environment value on the command line as such (this sets the parallel connections to 8)
export AZCOPY_CONCURRENCY_VALUE=8

And then in the same session, re-run the AzCopy command.

**Comment by epgui** [comment]
This appears to have fixed my issue, and my files have been transferred after following your suggestion. In the interim, to complicate debugging work as much as possible, I think I should mention that I have also moved to a different hotel (different network entirely) in a different city.

Thank you so much for your help!
