### ISSUE TITLE
Couldn't create job part plan file - too many open files - OSX

### ISSUE THREAD

**Issue by mpuhacz** [Azure/azure-storage-azcopy#907]
### Which version of the AzCopy was used? 
AzCopy 10.3.4

### Which platform are you using? (ex: Windows, Mac, Linux)
Mac
### What command did you run?
```
azcopy sync https://a1.blob.core.windows.net/c1 https://a2.blob.core.windows.net/c2 --exclude-pattern "..."  --recursive=true
```
### What problem was encountered?
```
Job e664fee5-9655-6642-6a25-6d2a572266bb has started
Log file is located at: /Users/puhaczm1/.azcopy/e664fee5-9655-6642-6a25-6d2a572266bb.log

13472 Files Scanned at Source, 96 Files Scanned at Destination, 2-sec Throughput (Mb/s): 0
13472 Files Scanned at Source, 96 Files Scanned at Destination, 2-sec Throughput (Mb/s): 0
47136 Files Scanned at Source, 96 Files Scanned at Destination, 2-sec Throughput (Mb/s): 5794.8622panic: couldn't create job part plan file "e664fee5-9655-6642-6a25-6d2a572266bb--00004.steV10": open /Users/puhaczm1/.azcopy/plans/e664fee5-9655-6642-6a25-6d2a572266bb--00004.steV10: too many open files

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/ste.JobPartPlanFileName.Create(0xc005746000, 0x32, 0xe664fee500000000, 0x2a6d256a66429655, 0x4bb662257, 0x30300000000, 0x0, 0x0, 0x0, 0xc00008e360, ...)
	github.com/Azure/azure-storage-azcopy/ste/JobPartPlanFileName.go:125 +0x1f05
github.com/Azure/azure-storage-azcopy/ste.ExecuteNewCopyJobPartOrder(0xe664fee500000000, 0x2a6d256a66429655, 0x4bb662257, 0x30300000000, 0x0, 0x0, 0x0, 0xc00008e360, 0x45, 0xc0000d4200, ...)
	github.com/Azure/azure-storage-azcopy/ste/init.go:143 +0xb7
github.com/Azure/azure-storage-azcopy/cmd.inprocSend(0x476a1aa, 0x10, 0x4658660, 0xc0000ac780, 0x46586a0, 0xc005148380, 0x1, 0xc005148380)
	github.com/Azure/azure-storage-azcopy/cmd/rpc.go:44 +0x8cf
github.com/Azure/azure-storage-azcopy/cmd.glob..func4(0x476a1aa, 0x10, 0x4658660, 0xc0000ac780, 0x46586a0, 0xc005148380)
	github.com/Azure/azure-storage-azcopy/cmd/rpc.go:36 +0x5d
github.com/Azure/azure-storage-azcopy/cmd.(*copyTransferProcessor).sendPartToSte(0xc000302140, 0x0, 0xc0067923c0, 0x46)
	github.com/Azure/azure-storage-azcopy/cmd/zc_processor.go:124 +0x86
github.com/Azure/azure-storage-azcopy/cmd.(*copyTransferProcessor).scheduleCopyTransfer(0xc000302140, 0xc006792910, 0x4e, 0x0, 0xed581db32, 0xc000e8ede0, 0x100, 0xc00665e480, 0x10, 0x12, ...)
	github.com/Azure/azure-storage-azcopy/cmd/zc_processor.go:67 +0x260
github.com/Azure/azure-storage-azcopy/cmd.(*syncSourceComparator).processIfNecessary(0xc0000a0150, 0xc006792910, 0x4e, 0x0, 0xed581db32, 0xc000e8ede0, 0x100, 0xc00665e480, 0x10, 0x12, ...)
	github.com/Azure/azure-storage-azcopy/cmd/syncComparator.go:105 +0x2d5
github.com/Azure/azure-storage-azcopy/cmd.processIfPassedFilters(0xc0002a8700, 0x31, 0x38, 0xc006792910, 0x4e, 0x0, 0xed581db32, 0xc000e8ede0, 0x100, 0xc00665e480, ...)
	github.com/Azure/azure-storage-azcopy/cmd/zc_enumerator.go:582 +0xd6
github.com/Azure/azure-storage-azcopy/cmd.(*blobTraverser).traverse(0xc0001740c0, 0x0, 0xc0000a0160, 0xc0002a8700, 0x31, 0x38, 0x0, 0x0)
	github.com/Azure/azure-storage-azcopy/cmd/zc_traverser_blob.go:193 +0xd89
github.com/Azure/azure-storage-azcopy/cmd.(*syncEnumerator).enumerate(0xc000302190, 0x48ae600, 0xc00009b6b0)
	github.com/Azure/azure-storage-azcopy/cmd/zc_enumerator.go:508 +0xf1
github.com/Azure/azure-storage-azcopy/cmd.(*cookedSyncCmdArgs).process(0xc0000e2000, 0xdd4, 0x0)
	github.com/Azure/azure-storage-azcopy/cmd/sync.go:519 +0x252
github.com/Azure/azure-storage-azcopy/cmd.init.18.func2(0xc0002a1180, 0xc0000baaf0, 0x2, 0x5)
	github.com/Azure/azure-storage-azcopy/cmd/sync.go:554 +0x17e
github.com/spf13/cobra.(*Command).execute(0xc0002a1180, 0xc0000baaa0, 0x5, 0x5, 0xc0002a1180, 0xc0000baaa0)
	github.com/spf13/cobra@v0.0.3/command.go:766 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x4d4dfe0, 0xc00021fe00, 0x0, 0xffffffffffffffff)
	github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.3/command.go:800
github.com/Azure/azure-storage-azcopy/cmd.Execute(0xc0000ae920, 0x17, 0xc0000ae920, 0x17, 0xc0000ae980, 0x1d, 0x100)
	github.com/Azure/azure-storage-azcopy/cmd/root.go:110 +0xcf
main.main()
	github.com/Azure/azure-storage-azcopy/main.go:82 +0x3dd
```

**Comment by JohnRusk** [comment]
Please send us the first 20 or so lines of the log file: /Users/puhaczm1/.azcopy/e664fee5-9655-6642-6a25-6d2a572266bb.log

**Comment by mpuhacz** [comment]
```
➜ head -n 20 /Users/puhaczm1/.azcopy/e664fee5-9655-6642-6a25-6d2a572266bb.log

2020/03/16 14:46:46 AzcopyVersion  10.3.4
2020/03/16 14:46:46 OS-Environment  darwin
2020/03/16 14:46:46 OS-Architecture  amd64
2020/03/16 14:46:46 Log times are in UTC. Local time is 16 Mar 2020 15:46:46
2020/03/16 14:46:46 Job-Command sync ... --recursive=true
2020/03/16 14:46:46 Number of CPUs: 12
2020/03/16 14:46:46 Max file buffer RAM 6.000 GB
2020/03/16 14:46:46 Max concurrent network operations: 192 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2020/03/16 14:46:46 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2020/03/16 14:46:46 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2020/03/16 14:46:46 Max open files when downloading: 32 (auto-computed)
2020/03/16 14:46:46 JobID=e664fee5-9655-6642-6a25-6d2a572266bb, credential type: Anonymous
2020/03/16 14:46:46 scheduling JobID=e664fee5-9655-6642-6a25-6d2a572266bb, Part#=0, Transfer#=0, priority=0
2020/03/16 14:46:46 scheduling JobID=e664fee5-9655-6642-6a25-6d2a572266bb, Part#=0, Transfer#=1, priority=0
2020/03/16 14:46:46 scheduling JobID=e664fee5-9655-6642-6a25-6d2a572266bb, Part#=0, Transfer#=2, priority=0
2020/03/16 14:46:46 scheduling JobID=e664fee5-9655-6642-6a25-6d2a572266bb, Part#=0, Transfer#=3, priority=0
2020/03/16 14:46:46 scheduling JobID=e664fee5-9655-6642-6a25-6d2a572266bb, Part#=0, Transfer#=4, priority=0
2020/03/16 14:46:46 scheduling JobID=e664fee5-9655-6642-6a25-6d2a572266bb, Part#=0, Transfer#=5, priority=0
2020/03/16 14:46:46 scheduling JobID=e664fee5-9655-6642-6a25-6d2a572266bb, Part#=0, Transfer#=6, priority=0
2020/03/16 14:46:46 scheduling JobID=e664fee5-9655-6642-6a25-6d2a572266bb, Part#=0, Transfer#=7, priority=0```

**Comment by JohnRusk** [comment]
Perfect, thank you.  It looks like the reason for the problem is that your process is constrained to have only a small number of open file handles. On *nix-like OSs, including OSX, that is normally controlled by the `ulimit` settings for the process. (See https://ss64.com/osx/ulimit.html )  The setting in question is the "open files" one.

BTW, the way I can tell that you have a low ulimit on open file handles is that "max open files when downloading" is set to 32, which is a hard-coded floor set in the app. It would have been higher if you had a higher ulimit.

You have two choices for fixing this:
1. Increase the open files limit for the AzCopy process.   E.g. if your current setting is, say 256, try 1024.
2.  If you can't increase the limit, reducing AzCopy's handle consumption may solve it.  Set the environment variables AZCOPY_CONCURRENCY_VALUE and AZCOPY_CONCURRENT_FILES to values substantially lower than those shown in the log above. (E.g. 32 and 16 respectively).

**Comment by mpuhacz** [comment]
Thanks a lot, @JohnRusk!
