### ISSUE TITLE
Uploading file with 160 or more cyrillic symbols in url failes

### ISSUE THREAD

**Issue by GreatChieftain** [Azure/azure-storage-azcopy#945]
### Which version of the AzCopy was used? 
azcopy version 10.3.4

### Which platform are you using? (ex: Windows, Mac, Linux)
Windows

### What command did you run?
`.\azcopy copy 'D:\UPLOAD\0.5GB.zip' 'https://backuptest8253.blob.core.windows.net/backup/ыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыы/0.5GB.zip?{SAS}'`

### What problem was encountered?
When uploading file with more than 160 cyrillic symbols in URL occurs error:
```
panic: destination root string is too large: "https://backuptest8253.blob.core.windows.net/backup/%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B%D1%8B/0.5GB.zip"

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/ste.JobPartPlanFileName.Create(0xc00001ec40, 0x32, 0x682bbedc00000000, 0xde6e834bad4fc69f, 0x718228b7, 0x10300000001, 0x0, 0x0, 0x0, 0xc00001c800, ...)
        /home/vsts/work/1/s/ste/JobPartPlanFileName.go:78 +0x1f47
github.com/Azure/azure-storage-azcopy/ste.ExecuteNewCopyJobPartOrder(0x682bbedc00000000, 0xde6e834bad4fc69f, 0x718228b7, 0x10300000001, 0x0, 0x0, 0x0, 0xc00001c800, 0x19, 0xc0007d7800, ...)
        /home/vsts/work/1/s/ste/init.go:143 +0xbe
github.com/Azure/azure-storage-azcopy/cmd.inprocSend(0xbb42d0, 0x10, 0xa91000, 0xc00009af00, 0xa91040, 0xc0002133a0, 0x1, 0xc0002133a0)
        /home/vsts/work/1/s/cmd/rpc.go:44 +0x8d3
github.com/Azure/azure-storage-azcopy/cmd.glob..func4(0xbb42d0, 0x10, 0xa91000, 0xc00009af00, 0xa91040, 0xc0002133a0)
        /home/vsts/work/1/s/cmd/rpc.go:36 +0x64
github.com/Azure/azure-storage-azcopy/cmd.dispatchFinalPart(0xc00009af00, 0xc000050e00, 0x0, 0x0)
        /home/vsts/work/1/s/cmd/copyEnumeratorHelper.go:63 +0xcd
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).initEnumerator.func6(0xc000213220, 0x0)
        /home/vsts/work/1/s/cmd/copyEnumeratorInit.go:242 +0x3a
github.com/Azure/azure-storage-azcopy/cmd.(*copyEnumerator).enumerate(0xc0007e00c0, 0x682bbedc00000000, 0xde6e834bad4fc69f)
        /home/vsts/work/1/s/cmd/zc_enumerator.go:558 +0x9f
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).processCopyJobPartOrders(0xc000050e00, 0x0, 0x0)
        /home/vsts/work/1/s/cmd/copy.go:983 +0x71a
github.com/Azure/azure-storage-azcopy/cmd.(*cookedCopyCmdArgs).process(0xc000050e00, 0x7c4, 0xb)
        /home/vsts/work/1/s/cmd/copy.go:766 +0x8b
github.com/Azure/azure-storage-azcopy/cmd.init.2.func2(0xc0001d9900, 0xc000212140, 0x2, 0x2)
        /home/vsts/work/1/s/cmd/copy.go:1348 +0x19d
github.com/spf13/cobra.(*Command).execute(0xc0001d9900, 0xc0002120a0, 0x2, 0x2, 0xc0001d9900, 0xc0002120a0)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x11a8040, 0xc00001e9c0, 0xc00013bdc8, 0x40d06f)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2f1
github.com/spf13/cobra.(*Command).Execute(...)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/Azure/azure-storage-azcopy/cmd.Execute(0xc00001d140, 0x19, 0xc00001d140, 0x19, 0xc00001d180, 0x1f, 0x7fffffff)
        /home/vsts/work/1/s/cmd/root.go:110 +0xd6
main.main()
        /home/vsts/work/1/s/main.go:82 +0x3cb
```
azcopy 8.1.0 executes similar command without errors

### How can we reproduce the problem in the simplest way?
Upload file with 160 or more cyrillic symbols in URL to file or blob storage 

### Have you found a mitigation/solution?
No

**Comment by JohnRusk** [comment]
Thanks for logging this.  There is indeed a length limit in the code, and its probably a bit too small.  But it's only a limit on what we call the root path.  So you could probably work around it like this: (I haven't tested this myself)

Put the file localling into a directory with the right Cyrillic names. E.g. 
c:\upload\ыыыы....ыыыы\0.5GB.zip

Then copy the "upload" directory (so that is the root) but filter to just the path you want.  Like this:

```
.\azcopy copy 'D:\UPLOAD\*' 'https://backuptest8253.blob.core.windows.net/backup?{SAS}' --include-path ыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыы
--include-pattern 0.5GB.zip ```
Note three things:
the \* after D:\Upload
The use of include path (to move the long string out of the "root" URL)
The fact that you need include-pattern to restrict it back to the specific file that you want to move

Note again that I have not tested this myself. So you'll need to test this workaround carefully if you want to use it.

I will leave this issue open, because we should fix it in a future release.

**Comment by JasonYeMSFT** [comment]
Even not at the root, there still seems to be a limit on how long a path can be.
```
./azcopy copy "/Users/username/Desktop/code.js" "https://acctname.blob.core.windows.net/bc0/longPath/NewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNewFoldernNe/code.js?SAS"
```

AzCopy will throw the same error.
https://github.com/microsoft/AzureStorageExplorer/issues/4752
