### ISSUE TITLE
azcopy crash while recursively copying a dir from local to azure storage

### ISSUE THREAD

**Issue by abrahaej** [Azure/azure-storage-azcopy#947]
##### Note: The version is visible when running AzCopy without any argument
10.3.4
### Which platform are you using? (ex: Windows, Mac, Linux) 
Linux
Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

##### Note: Please remove the SAS to avoid exposing your credentials. If you cannot remember the exact command, please retrieve it from the beginning of the log file.

 I am transferring about 216Gb of data, consisting of a hierarchy of directories and files. Files range in size from a few Mb to 10Gb

I first authenticated with this command:
azcopy login --tenant-id "my-tenant-id"

then I ran this command:
azcopy copy 'base_of_source_dir 'https://(redacted).blob.core.windows.net/media'  --recursive

and this went on succefully for about 19% of the job then it crashed. (so indeed I see files/dirs that have been copied over to my storage account). Every time I try to resume the job with this command:

azcopy jobs --cap-mbps 1 resume 'redacted-job-name'

I get a crash. I've attached the last crash's stack trace.

### What problem was encountered?
crashed. I attached a full stack trace and error dump, but here's the first few lines;

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x44e7f9]

goroutine 18 [running]:
runtime.throw(0xb9d0b7, 0x2a)

/opt/hostedtoolcache/go/1.13.0/x64/src/runtime/panic.go:774 +0x72 fp=0xc000043730 sp=0xc000043700 pc=0x4303a2
runtime.sigpanic()

/opt/hostedtoolcache/go/1.13.0/x64/src/runtime/signal_unix.go:378 +0x47c fp=0xc000043760 sp=0xc000043730 pc=0x44568c
runtime.timerproc(0x117d0c0)

/opt/hostedtoolcache/go/1.13.0/x64/src/runtime/time.go:276 +0xf9 fp=0xc0000437d8 sp=0xc000043760 pc=0x44e7f9
runtime.goexit()

/opt/hostedtoolcache/go/1.13.0/x64/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000437e0 sp=0xc0000437d8 pc=0x45dcd1
created by runtime.(*timersBucket).addtimerLocked

/opt/hostedtoolcache/go/1.13.0/x64/src/runtime/time.go:169 +0x10e

[azcopy_crash.txt.zip](https://github.com/Azure/azure-storage-azcopy/files/4432757/azcopy_crash.txt.zip)

### How can we reproduce the problem in the simplest way?
not sure. I am transferring about 216Gb of data, consisting of a hierarchy of directories and files. Files range in size from a few Mb to 10Gb

### Have you found a mitigation/solution?
No! It crashes every time I resume the job.

**Comment by JohnRusk** [comment]
Hmm. Looks like this error: https://github.com/golang/go/issues/24790  (which is not well-described there, in terms of possible causes).

It's a timer issue, and at this stage I don't know whether its our bug or the runtime's bug, and I don't know which timer may be involved.  I think we have a refresh timer to check if authentication tokens have expired.  If you're lucky, it will be _that_ timer, and you can workaround the issue by running `azcopy logout` then resuming the job with SAS authentication. (I _think_ it's possible to supply a SAS when resuming a job that was originally authenticated with login. See docs for azcopy jobs resume).

By the way, in your earlier attempts, when you resume, how soon does it crash?

When it originally failed at around 19%, do you recall approximately how many minutes it had been running for?

**Comment by abrahaej** [comment]
hi, thanks for looking.

the first time I ran it, it ran overnight (I don't have a super-fast pipe), then it crashed. After that, I'd resume, and it would crash "soon thereafter" meaning within a matter of a few hours (sorry I can't be more exact). of course, I'd do an 'azcopy login' each time before I resume.

Interestingly, the status line goes above 19% with every resume, but then once it crashes and I re-resume, it goes back to 19% so not sure what is going on there...

Are you saying that I could use SAS from the getgo without login, and circumvent this whole issue?! (provided I start from scratch)

**Comment by JohnRusk** [comment]
I'm saying you could use SAS from where you are right now. Ie.. you probably do not need to start from scratch.

(I have never tested resuming with SAS after starting with login, but I can't think of any reason why it wouldn't work).

**Comment by abrahaej** [comment]
I managed to resume with SAS. I'll keep an eye on it. I made the key valid through Saturday. that should be enough at a 2Mbps choke.

Thanks for the hints.

**Comment by abrahaej** [comment]
update: after running for approx. 1.5 hours, as I was monitoring azcopy's status line, I suddenly lost the connection. The machine was no longer responsive (no ping) and I had to hard-reset it. The /var/log/syslog had nothing unusual, but the /var/log/messages had lots of azcopy-related messages, I hesitate to paste them here with no knowledge of their security aspect, but here's an excerpt that seems benign:

Apr  5 20:34:41 ns2 azcopy[30609]: 2020/04/05 20:34:41 ==> REQUEST/RESPONSE (Try=4/15m0.000342658s[SLOW >3s], OpTime=1h0m12.376711972s) -- REQUEST ERROR#012   PUT https:[...]ERROR:#012-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/error.go:154#012HTTP request failed#012#012Put https:[...]

not sure what to make of this... but I still am at 19% - so it ran  --and I could actually see that data was being sent out at the desired rate of 2mbps by monitoring the gateway-- for an hour and a half - and the %completed never went above 19! if, for instance, one of the files was a bit larger, say 10Gb, would it stay at 19% until it uploads the entire file? that would explain it. also, how can I find out what file(s) azcopy is actually copying at the moment?

**Comment by JohnRusk** [comment]
Sorry to hear you're having so much trouble.

Yes, it would stay at 19% until it uploads the whole file.

If you look at the azCopy log file, it will probably show which files its copying at the time, because it will be logging HTTP operations against them. (Although its hard to get a full list).

From the log, it looks like you're getting lots of timeouts, due to the small network bandwidth.

There are three things you can do when you run it next time:
1. Set the environment variable AZCOPY_CONCURRENCY_VALUE to "AUTO".  That helps a lot in low-bandwidth cases, since it results in AzCopy using far fewer connections that normal.
1. Set the environment variable AZCOPY_CONCURRENT_FILES to 1 if your files are big, or to about 4 if they are small.  (The default is 64, but it will help to use something much lower in your case, so that if it fails ,it's more likely to fail after, say, fully completeing 5 files - versus partially completing 50)
1. Probably also give it an explicit speed cap, by adding this to the command line:  --cap-mbps 2

All of of those should work with resume.  If you try them all, I think the might help a lot.

**Comment by abrahaej** [comment]
I've been doing (3) but I will certainly try (1) and (2).

Thanks again - I didn't mean for this to become a customer support ticket :-) but I very much appreciate the help.

I also monitored the cpu temperature and other oddities but nothing like that appears suspect.

just one last question: suppose one of the files is corrupt - that wouldn't cause it to keel over like this would it?

**Comment by JohnRusk** [comment]
That would not cause it to keel over.

Please let us know how you go.

BTW, I'm not sure what to think about the original crash issue. If you continue to _not_ see it  when using the SAS token, we might conclude that it involves the token refresh timer.

**Comment by abrahaej** [comment]
Just wanted to report that after I used the envariables you recommended above, my azcopy file transfer has been going fine, one file at a time :-) but going nevertheless. No crashes. As such, I suppose I'll close this issue. Also, using sas definitely was better than login, since I have control over how long the session is valid for. Thanks for your help.

**Comment by JohnRusk** [comment]
Thanks for the update. Glad to hear this issue is solved for you.

I'm actually going to re-open the issue, to remind _us_ to look into the timer refresh issue, in case there is in fact a problem there.

**Comment by gapra-msft** [comment]
Hi, AzCopy has since moved away from implementing our own token credentials since upgrading to the new Azure Identity library, so this issue is no longer applies. Closing this issue as a result. In case you hit any other problems feel free to open a new issue and we are happy to take a look.
